name: UAT CI/CD Pipeline
on:
  push:
    branches:
      - uat

jobs:
  build:
    runs-on: bb-uat

    strategy:
      matrix:
        node-version:
          - 20.x

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cp /home/ec2-user/uat/secret/.env /home/ec2-user/uat/bb-backend/_work/bridgebio-backend/bridgebio-backend/.env
    - run: npm i
    - run: npm run build
    - run: pm2 delete bb-backend-uat
    - run: pm2 start npm --name "bb-backend-uat" -- start
