name: Production CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: production-backend

    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cp /home/ubuntu/restat/production/backend/.env /home/ubuntu/restat/production/backend-pipeline/_work/restat-backend/restat-backend/.env
    - run: npm i --legacy-peer-deps
    - run: npm run build
    - run: pm2 delete restat-backend-production
    - run: pm2 start npm --name "restat-backend-production" -- start
