export const PORTFOLIO_TYPE = {
    TEMPLATE: 'TEMPLATE',
    CASE_STUDY: 'CASE_STUDY',
    PROJECT: 'PROJECT',
    CODE_SNIPPET: 'CODE_SNIPPET',
    TEXT_SNIPPET: 'TEXT_SNIPPET',
    LINK: 'LINK',
};