"""Simplify face alert profile

Revision ID: 025c4846e84c
Revises: b5acec5e9072
Create Date: 2023-10-19 15:00:02.187991

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "025c4846e84c"
down_revision = "b5acec5e9072"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unique_faces_to_alert_profiles")
    op.create_unique_constraint(
        "uc_unique_faces_unique_face_id", "unique_faces", ["unique_face_id"]
    )
    op.add_column(
        "face_alert_profiles", sa.Column("unique_face_id", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        "fk_face_alert_profiles_unique_faces_unique_face_id",
        "face_alert_profiles",
        "unique_faces",
        ["unique_face_id"],
        ["unique_face_id"],
        ondelete="CASCADE",
    )
    op.drop_column("face_alert_profiles", "face_s3_path")
    op.drop_constraint(
        "face_occurrences_unique_face_id_nvr_uuid_fkey",
        "face_occurrences",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_face_occurrences_unique_faces_unique_face_id",
        "face_occurrences",
        "unique_faces",
        ["unique_face_id"],
        ["unique_face_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_face_occurrences_unique_faces_unique_face_id",
        "face_occurrences",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "face_occurrences_unique_face_id_nvr_uuid_fkey",
        "face_occurrences",
        "unique_faces",
        ["unique_face_id", "nvr_uuid"],
        ["unique_face_id", "nvr_uuid"],
        ondelete="CASCADE",
    )
    op.add_column(
        "face_alert_profiles",
        sa.Column("face_s3_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fk_face_alert_profiles_unique_faces_unique_face_id",
        "face_alert_profiles",
        type_="foreignkey",
    )
    op.drop_column("face_alert_profiles", "unique_face_id")
    op.drop_constraint("uc_unique_faces_unique_face_id", "unique_faces", type_="unique")
    op.create_table(
        "unique_faces_to_alert_profiles",
        sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("unique_face_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("nvr_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["face_alert_profiles.id"],
            name="unique_faces_to_alert_profiles_profile_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unique_face_id", "nvr_uuid"],
            ["unique_faces.unique_face_id", "unique_faces.nvr_uuid"],
            name="unique_faces_to_alert_profiles_unique_face_id_nvr_uuid_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "unique_face_id", "nvr_uuid", name="unique_faces_to_alert_profiles_pkey"
        ),
    )
    # ### end Alembic commands ###
