"""make last run trigger type dependent

Revision ID: 07a1f9ffb13d
Revises: 4d94f476ff21
Create Date: 2023-05-22 20:36:39.152127

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07a1f9ffb13d"
down_revision = "4d94f476ff21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_alert_last_run",
        sa.Column(
            "trigger_type",
            sa.Enum("DO_NOT_ENTER", "SHORT_STICK_AROUND", "IDLING", name="triggertype"),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "user_alert_last_run_trigger_type_fkey",
        "user_alert_last_run",
        "user_alert_trigger_types",
        ["trigger_type"],
        ["trigger_type"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_alert_last_run_trigger_type_fkey",
        "user_alert_last_run",
        type_="foreignkey",
    )
    op.drop_column("user_alert_last_run", "trigger_type")
    # ### end Alembic commands ###
