"""generate_tables_for_mct

Revision ID: 13b8ad274ffe
Revises: 543ca23e8768
Create Date: 2023-06-21 19:28:00.558657

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13b8ad274ffe"
down_revision = "543ca23e8768"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journey_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mac_address", sa.String(), nullable=False),
        sa.Column("object_min_x", sa.Float(), nullable=False),
        sa.Column("object_min_y", sa.Float(), nullable=False),
        sa.Column("object_max_x", sa.Float(), nullable=False),
        sa.Column("object_max_y", sa.Float(), nullable=False),
        sa.Column("object_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("request_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "embedding_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("embedding", sa.ARRAY(sa.Float()), nullable=True),
        sa.ForeignKeyConstraint(["request_id"], ["journey_requests.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embedding_responses_request_id"),
        "embedding_responses",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_embedding_responses_request_id"), table_name="embedding_responses"
    )
    op.drop_table("embedding_responses")
    op.drop_table("journey_requests")
    # ### end Alembic commands ###
