"""add s3 path and area to license plate alert

Revision ID: 1e40556373eb
Revises: 82d1e5a046e8
Create Date: 2024-01-29 15:16:17.232662

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e40556373eb"
down_revision = "82d1e5a046e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # drop all existing alert profiles rows, users have not created any yet
    op.execute("DELETE FROM license_plate_alert_profiles")
    op.add_column(
        "license_plate_alert_profiles",
        sa.Column("image_s3_path", sa.String(), nullable=False),
    )
    op.add_column(
        "license_plate_alert_profiles", sa.Column("x_min", sa.Float(), nullable=False)
    )
    op.add_column(
        "license_plate_alert_profiles", sa.Column("y_min", sa.Float(), nullable=False)
    )
    op.add_column(
        "license_plate_alert_profiles", sa.Column("x_max", sa.Float(), nullable=False)
    )
    op.add_column(
        "license_plate_alert_profiles", sa.Column("y_max", sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("license_plate_alert_profiles", "y_max")
    op.drop_column("license_plate_alert_profiles", "x_max")
    op.drop_column("license_plate_alert_profiles", "y_min")
    op.drop_column("license_plate_alert_profiles", "x_min")
    op.drop_column("license_plate_alert_profiles", "image_s3_path")
    # ### end Alembic commands ###
