"""refactor text search response table

Revision ID: 29282da60850
Revises: ea4a40a71921
Create Date: 2023-04-15 02:09:05.032094

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "29282da60850"
down_revision = "ea4a40a71921"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_search_response",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("nvr_uuid", sa.String(), nullable=False),
        sa.Column("ranked_timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("mac_address", sa.String(), nullable=False),
        sa.Column("ranked_object_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["request_id"], ["text_search_requests.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_text_search_response_id"), "text_search_response", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_text_search_response_request_id"),
        "text_search_response",
        ["request_id"],
        unique=False,
    )
    op.drop_index(
        "ix_text_search_responses_request_id", table_name="text_search_responses"
    )
    op.drop_table("text_search_responses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_search_responses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("nvr_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "ranked_timestamps",
            postgresql.ARRAY(postgresql.TIMESTAMP(timezone=True)),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "scores",
            postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "mac_addresses",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ranked_object_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["text_search_requests.id"],
            name="text_search_responses_request_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="text_search_responses_pkey"),
        sa.UniqueConstraint(
            "request_id",
            "nvr_uuid",
            name="text_search_responses_request_id_nvr_uuid_key",
        ),
    )
    op.create_index(
        "ix_text_search_responses_request_id",
        "text_search_responses",
        ["request_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_text_search_response_request_id"), table_name="text_search_response"
    )
    op.drop_index(op.f("ix_text_search_response_id"), table_name="text_search_response")
    op.drop_table("text_search_response")
    # ### end Alembic commands ###
