"""Add Location id to Access Points

Revision ID: 2ab298290a74
Revises: 017e013aab75
Create Date: 2023-11-24 11:33:53.963903

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ab298290a74"
down_revision = "017e013aab75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "access_points", sa.Column("location_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_access_points_location_id",
        "access_points",
        "locations",
        ["location_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_access_points_location_id", "access_points", type_="foreignkey"
    )
    op.drop_column("access_points", "location_id")
    # ### end Alembic commands ###
