"""add new column and not nullable

Revision ID: 302a420bc3c2
Revises: 89becb141a4a
Create Date: 2023-04-11 23:55:53.496316

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "302a420bc3c2"
down_revision = "89becb141a4a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "perception_object_events",
        sa.Column(
            "object_idx", sa.Integer(), nullable=False, default=0, server_default="0"
        ),
    )
    # Remove the server_default value after adding the new colum
    op.alter_column("perception_object_events", "object_idx", server_default=None)

    op.add_column(
        "text_search_responses",
        sa.Column(
            "ranked_object_ids",
            postgresql.ARRAY(sa.Integer()),
            nullable=False,
            server_default="{}",
        ),
    )
    # Remove the server_default value after adding the new colum
    op.alter_column("text_search_responses", "ranked_object_ids", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("text_search_responses", "ranked_object_ids")
    op.drop_column("perception_object_events", "object_idx")
    # ### end Alembic commands ###
