"""use set null for access point location

Revision ID: 3e70ed8eebff
Revises: 7b8ed7cfaae7
Create Date: 2024-04-15 15:20:44.946034

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e70ed8eebff"
down_revision = "7b8ed7cfaae7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_access_points_location_id", "access_points", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_access_points_location_id",
        "access_points",
        "locations",
        ["location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_access_points_location_id", "access_points", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_access_points_location_id",
        "access_points",
        "locations",
        ["location_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
