"""allow only one profile per face

Revision ID: 41f970f2ddd8
Revises: 3e70ed8eebff
Create Date: 2024-04-23 11:24:12.367226

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "41f970f2ddd8"
down_revision = "3e70ed8eebff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uc_face_alert_profiles_org_unique_face_id",
        "face_alert_profiles",
        ["org_unique_face_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uc_face_alert_profiles_org_unique_face_id",
        "face_alert_profiles",
        type_="unique",
    )
    # ### end Alembic commands ###
