"""Add composite index for face occurrence time and mac addr

Revision ID: 43bee3de0688
Revises: 702f1a0f7790
Create Date: 2023-09-28 18:06:09.636487

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "43bee3de0688"
down_revision = "702f1a0f7790"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "face_occurrence_time_mac_address_idx",
        "face_occurrences",
        ["occurrence_time", "mac_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("face_occurrence_time_mac_address_idx", table_name="face_occurrences")
    # ### end Alembic commands ###
