"""add hls session

Revision ID: 4d94f476ff21
Revises: 80178610c5a9
Create Date: 2023-05-19 14:10:06.656317

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d94f476ff21"
down_revision = "80178610c5a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hls_sessions",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("stream_name", sa.String(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("token", "stream_name", "start_time", "end_time"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hls_sessions")
    # ### end Alembic commands ###
