"""Add org network scan settings

Revision ID: 63630ec31ffc
Revises: 5563572938a2
Create Date: 2024-03-21 11:26:51.620042

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "63630ec31ffc"
down_revision = "5563572938a2"
branch_labels = None
depends_on = None

DEFAULT_NETWORK_SCAN_SETTINGS = '\'{"mode": "auto"}\'::jsonb'


def upgrade() -> None:
    op.add_column(
        "organizations",
        sa.Column(
            "network_scan_settings",
            sa.JSON(),
            nullable=False,
            server_default=sa.text(DEFAULT_NETWORK_SCAN_SETTINGS),
            default=sa.text(DEFAULT_NETWORK_SCAN_SETTINGS),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "network_scan_settings")
    # ### end Alembic commands ###
