"""mct images table

Revision ID: 73f5f6c633e0
Revises: 8d1d1644d9b3
Create Date: 2023-07-18 16:25:56.601029

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73f5f6c633e0"
down_revision = "8d1d1644d9b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mct_images",
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("camera_mac_address", sa.String(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("perception_stack_start_id", sa.String(), nullable=False),
        sa.Column("s3_path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_mac_address"], ["cameras.mac_address"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("timestamp", "camera_mac_address", "track_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mct_images")
    # ### end Alembic commands ###
