"""add per camera webrtc flag

Revision ID: 7cbfdcc2aa72
Revises: bc589465f094
Create Date: 2023-11-06 23:19:35.415269

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cbfdcc2aa72"
down_revision = "bc589465f094"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "cameras",
        sa.Column(
            "is_webrtc_enabled", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "is_webrtc_enabled")
    # ### end Alembic commands ###
