"""Remove user alert last run table

Revision ID: 7d384d81429b
Revises: 302d198323cd
Create Date: 2024-02-26 10:31:08.177018

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7d384d81429b"
down_revision = "302d198323cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_alert_last_run")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.create_table(
        "user_alert_last_run",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "last_run",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            postgresql.ENUM(
                "DO_NOT_ENTER",
                "SHORT_STICK_AROUND",
                "IDLING",
                name="triggertype",
                create_type=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["trigger_type"],
            ["user_alert_trigger_types.trigger_type"],
            name="user_alert_last_run_trigger_type_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="user_alert_last_run_pkey"),
    )
    # ### end Alembic commands ###
