"""Test migrations rollback 2.

Revision ID: 82d1e5a046e8
Revises: ae3c9b582780
Create Date: 2024-01-26 17:57:21.596453

"""

# revision identifiers, used by Alembic.
revision = "82d1e5a046e8"
down_revision = "ae3c9b582780"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
