"""generate_journey_response_tables

Revision ID: 859164a00795
Revises: 6205c0cf6cae
Create Date: 2023-06-23 18:22:24.582837

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "859164a00795"
down_revision = "6205c0cf6cae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journey_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("nvr_uuid", sa.String(), nullable=False),
        sa.Column("mac_address", sa.String(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("object_idx", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["request_id"], ["journey_requests.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journey_responses_request_id"),
        "journey_responses",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_journey_responses_request_id"), table_name="journey_responses"
    )
    op.drop_table("journey_responses")
    # ### end Alembic commands ###
