"""Add number licensed cameras to organization

Revision ID: 89b38f1fe214
Revises: 30ac3a68984b
Create Date: 2024-03-04 14:41:15.651214

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "89b38f1fe214"
down_revision = "30ac3a68984b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "number_licensed_cameras",
            sa.Integer(),
            server_default=sa.text("NULL"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "number_licensed_cameras")
    # ### end Alembic commands ###
