"""update search table

Revision ID: 89becb141a4a
Revises: a9a3352b3b36
Create Date: 2023-04-06 18:27:10.729034

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "89becb141a4a"
down_revision = "a9a3352b3b36"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_search_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mac_addresses", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("text_query", sa.String(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("query_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_text_search_requests_id"), "text_search_requests", ["id"], unique=False
    )
    op.create_table(
        "text_search_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("nvr_uuid", sa.String(), nullable=False),
        sa.Column(
            "ranked_timestamps",
            postgresql.ARRAY(sa.TIMESTAMP(timezone=True)),
            nullable=False,
        ),
        sa.Column("scores", postgresql.ARRAY(sa.Float()), nullable=False),
        sa.Column("mac_addresses", postgresql.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(["request_id"], ["text_search_requests.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "nvr_uuid"),
    )
    op.create_index(
        op.f("ix_text_search_responses_request_id"),
        "text_search_responses",
        ["request_id"],
        unique=False,
    )
    op.drop_table("text_searches")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_searches",
        sa.Column("request_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("stream_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("text_query", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "ranked_timestamps",
            postgresql.ARRAY(postgresql.TIMESTAMP(timezone=True)),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("request_uuid", name="text_searches_pkey"),
    )
    op.drop_index(
        op.f("ix_text_search_responses_request_id"), table_name="text_search_responses"
    )
    op.drop_table("text_search_responses")
    op.drop_index(op.f("ix_text_search_requests_id"), table_name="text_search_requests")
    op.drop_table("text_search_requests")
    # ### end Alembic commands ###
