"""Add is_favorite flag to access_points_cameras

Revision ID: 9e4e578bbe2f
Revises: 2ab298290a74
Create Date: 2023-11-29 12:59:35.114914

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e4e578bbe2f"
down_revision = "2ab298290a74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "access_points_cameras",
        sa.Column(
            "is_favorite",
            sa.Boolean(),
            default=False,
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("access_points_cameras", "is_favorite")
    # ### end Alembic commands ###
