"""Remove dashboard user view logs & user favorite

Revision ID: a6f02983c0b6
Revises: 9730212d35c1
Create Date: 2024-02-29 19:47:28.386619

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a6f02983c0b6"
down_revision = "9730212d35c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboard_user_preferences")
    op.drop_table("dashboard_user_view_logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_user_view_logs",
        sa.Column(
            "tenant",
            sa.VARCHAR(),
            server_default=sa.text("'unassigned'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("dashboard_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dashboard_id"],
            ["dashboards.id"],
            name="dashboard_user_view_logs_dashboard_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant"],
            ["organizations.tenant"],
            name="dashboard_user_view_logs_tenant_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="dashboard_user_view_logs_pkey"),
        sa.UniqueConstraint(
            "user_email",
            "dashboard_id",
            name="dashboard_user_view_logs_user_email_dashboard_id_key",
        ),
    )
    op.create_table(
        "dashboard_user_preferences",
        sa.Column(
            "tenant",
            sa.VARCHAR(),
            server_default=sa.text("'unassigned'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "favorite_dashboard_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["favorite_dashboard_id"],
            ["dashboards.id"],
            name="dashboard_user_preferences_favorite_dashboard_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant"],
            ["organizations.tenant"],
            name="dashboard_user_preferences_tenant_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="dashboard_user_preferences_pkey"),
        sa.UniqueConstraint(
            "user_email", name="dashboard_user_preferences_user_email_key"
        ),
    )
    # ### end Alembic commands ###
