"""Add camera faulty flag

Revision ID: a8c7aa845c21
Revises: 798eaaa21eb1
Create Date: 2023-09-04 11:00:10.483790

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8c7aa845c21"
down_revision = "798eaaa21eb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cameras",
        sa.Column("is_faulty", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "is_faulty")
    # ### end Alembic commands ###
