"""Test migrations rollback.

Revision ID: ae3c9b582780
Revises: 58300d6724af
Create Date: 2024-01-26 10:54:25.813028

"""

# revision identifiers, used by Alembic.
revision = "ae3c9b582780"
down_revision = "58300d6724af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
