"""Add license plate table

Revision ID: afc11aee09a2
Revises: 078b7823e313
Create Date: 2023-11-17 19:35:32.034741

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "afc11aee09a2"
down_revision = "078b7823e313"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license_plates",
        sa.Column("license_plate_number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("license_plate_number"),
    )
    op.add_column(
        "license_plate_detections",
        sa.Column("license_plate_number", sa.String(), nullable=True),
    )
    op.create_foreign_key(
        "fk_license_plate_detections_license_plates_license_plate_number",
        "license_plate_detections",
        "license_plates",
        ["license_plate_number"],
        ["license_plate_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_license_plate_detections_license_plates_license_plate_number",
        "license_plate_detections",
        type_="foreignkey",
    )
    op.drop_column("license_plate_detections", "license_plate_number")
    op.drop_table("license_plates")
    # ### end Alembic commands ###
