"""add nvr video log retention days

Revision ID: be46ce578090
Revises: 8457265657b7
Create Date: 2023-09-15 06:30:50.628485

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be46ce578090"
down_revision = "8457265657b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nvrs", sa.Column("retention_days", sa.Integer(), server_default="30")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nvrs", "retention_days")
    # ### end Alembic commands ###
