"""add text response status table

Revision ID: e11ddc590f3c
Revises: 493b01b0bd8b
Create Date: 2023-05-31 18:11:09.625622

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e11ddc590f3c"
down_revision = "493b01b0bd8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_search_response_status",
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("nvr_uuid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["request_id"], ["text_search_requests.id"]),
        sa.PrimaryKeyConstraint("request_id", "nvr_uuid"),
    )
    op.create_index(
        op.f("ix_text_search_response_status_request_id"),
        "text_search_response_status",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_text_search_response_status_request_id"),
        table_name="text_search_response_status",
    )
    op.drop_table("text_search_response_status")
    # ### end Alembic commands ###
