"""add license plate flag to camera

Revision ID: fc4be6b984a7
Revises: 859164a00795
Create Date: 2023-07-04 17:13:11.505516

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc4be6b984a7"
down_revision = "859164a00795"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "cameras",
        sa.Column(
            "is_license_plate_detection_enabled",
            sa.Boolean(),
            nullable=False,
            default=False,
            server_default="false",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "is_license_plate_detection_enabled")
    # ### end Alembic commands ###
