name: Lint
on:
  pull_request:
    branches: [master, uat, staging]

permissions:
  actions: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx affected -t lint --base=remotes/origin/${{ github.base_ref }} --head=HEAD
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
