export enum ActiveModulesPdf {
  INCIDENT_FUTURE = 'Incidents Tracking',
  DOT_MAP_SERVICE = 'Dot Map System',
  CAMPING_FUTURE = 'Camping Management',
  TRANSPORTATION_FUTURE = 'Transportation System',
  INVENTORY_FUTURE = 'Asset Tracking',
  SERVICE_REQUEST_FUTURE = 'Service Management',
  STAFF_FUTURE = 'Workforce',
  MESSAGE_SERVICE = 'Communication System',
  VENDOR_FUTURE = 'Vendor Portal',
}

export enum PdfTypes {
  EVENT_DETAIL = 'EVENT_DETAIL',
  COMPANY_DETAIL = 'COMPANY_DETAIL',
  SUB_COMPANY_DETAIL = 'SUB_COMPANY_DETAIL',
  SUB_COMPANIES_WITH_EVENTS = 'SUB_COMPANIES_WITH_EVENTS',
  COMPANIES_LISTING = 'COMPANIES_LISTING',
  EJECTION_FORM = 'EJECTION_FORM',
  EVENT_INCIDENT_REPORT_INCIDENT_TYPES = 'EVENT_INCIDENT_REPORT_INCIDENT_TYPES',
  EVENT_NOTES = 'EVENT_NOTES',
  PRE_EVENT_CHECKLIST = 'PRE_EVENT_CHECKLIST',
  DAY_OF_SHOW_CHECKLIST = 'DAY_OF_SHOW_CHECKLIST',
  EVENT_INCIDENT_REPORT = 'EVENT_INCIDENT_REPORT',
  INCIDENT_DASHBOARD_REPORT = 'INCIDENT_DASHBOARD_REPORT',
  COMPARISON_GRAPH = 'COMPARISON_GRAPH',
  WORKFORCE_USERS = 'WORKFORCE_USERS',
  AUDIT_REPORT = 'AUDIT_REPORT',
  INCIDENT_BY_DIVISION = 'INCIDENT_BY_DIVISION',
  INCIDENT_BY_ZONE = 'INCIDENT_BY_ZONE',
  INCIDENT_DASHBOARD_OVERVIEW_NEW = 'INCIDENT_DASHBOARD_OVERVIEW_NEW',
  WORKFORCE_STAFF_MAP_VIEW = 'WORKFORCE_STAFF_MAP_VIEW',
  DOTMAP_CONTRACT_ASSIGNMENT = 'DOTMAP_CONTRACT_ASSIGNMENT',
  DOTMAP_DEPLOYMENT_MAP = 'DOTMAP_DEPLOYMENT_MAP',
}

export enum CsvOrPdf {
  CSV = 'csv',
  PDF = 'pdf',
}
