export enum RolesNumberEnum {
  SUPER_ADMIN = 0,
  ADMIN = 1,
  DRIVER = 2,
  MANAGER = 3,
  SCANNER = 13,
  VENDOR = 14,
  CAMPING_ADMIN = 15,
  CAMPING_MANAGER = 16,
  VENDOR_STAFF = 18,
  TRANSPORT_MANAGER = 19,
  TRANSPORT_DISPATCHER = 20,
  CAMPING_DISPATCHER = 21,
  INCIDENT_MANAGER = 22,
  INCIDENT_DISPATCHER = 23,
  SERVICE_MANAGER = 24,
  SERVICE_DISPATCHER = 25,
  GLOBAL_ADMIN = 26,
  GLOBAL_MANAGER = 27,
  ONTRACK_MANAGER = 28,
  WORKFORCE_MANAGER = 29,
  OPERATIONS_MANAGER = 30,
  CAMERA_VENDOR = 31,
  REGIONAL_MANAGER = 32,
  REGIONAL_ADMIN = 33,
  REFERENCE_USER = 34,
  TASK_ADMIN = 35,
  LEGAL_ADMIN = 36,
  DOTMAP_ADMIN = 37,
}

export enum RolesEnum {
  SUPER_ADMIN = 'super_admin',
  ADMIN = 'admin',
  DRIVER = 'driver',
  MANAGER = 'manager',
  SCANNER = 'scanner',
  VENDOR = 'vendor',
  CAMPING_ADMIN = 'camping_admin',
  CAMPING_MANAGER = 'camping_manager',
  VENDOR_STAFF = 'vendor_staff',
  TRANSPORT_MANAGER = 'transport_manager',
  TRANSPORT_DISPATCHER = 'transport_dispatcher',
  CAMPING_DISPATCHER = 'camping_dispatcher',
  INCIDENT_MANAGER = 'incident_manager',
  INCIDENT_DISPATCHER = 'incident_dispatcher',
  SERVICE_MANAGER = 'service_manager',
  SERVICE_DISPATCHER = 'service_dispatcher',
  GLOBAL_ADMIN = 'global_admin',
  GLOBAL_MANAGER = 'global_manager',
  ONTRACK_MANAGER = 'ontrack_manager',
  WORKFORCE_MANAGER = 'workforce_manager',
  OPERATIONS_MANAGER = 'operations_manager',
  CAMERA_VENDOR = 'camera_vendor',
  REGIONAL_MANAGER = 'regional_manager',
  REGIONAL_ADMIN = 'regional_admin',
  REFERENCE_USER = 'reference_user',
  TASK_ADMIN = 'task_admin',
  LEGAL_ADMIN = 'legal_admin',
  DOTMAP_ADMIN = 'dotmap_admin',
}

export enum FormattedRolesEnum {
  SUPER_ADMIN = 'Super Admin',
  ADMIN = 'Admin',
  DRIVER = 'Driver',
  MANAGER = 'Manager',
  CRAIGS_STAGING = 'Craigs Staging',
  SCANNER = 'Scanner',
  VENDOR = 'Vendor',
  CAMPING_ADMIN = 'Camping Admin',
  CAMPING_MANAGER = 'Camping Manager',
  VENDOR_STAFF = 'Vendor Staff',
  TRANSPORT_MANAGER = 'Transport Manager',
  TRANSPORT_DISPATCHER = 'Transport Dispatcher',
  CAMPING_DISPATCHER = 'Camping Dispatcher',
  INCIDENT_MANAGER = 'Incident Manager',
  INCIDENT_DISPATCHER = 'Incident Dispatcher',
  SERVICE_MANAGER = 'Service Manager',
  SERVICE_DISPATCHER = 'Service Dispatcher',
  GLOBAL_ADMIN = 'Global Admin',
  GLOBAL_MANAGER = 'Global Manager',
  ONTRACK_MANAGER = 'Ontrack Manager',
  WORKFORCE_MANAGER = 'Workforce Manager',
  OPERATIONS_MANAGER = 'Operations Manager',
  CAMERA_VENDOR = 'Camera Vendor',
  REGIONAL_MANAGER = 'Regional Manager',
  REGIONAL_ADMIN = 'Regional Admin',
  REFERENCE_USER = 'Reference User',
  TASK_ADMIN = 'Task Admin',
  LEGAL_ADMIN = 'Legal Admin',
  DOTMAP_ADMIN = 'Dotmap Admin',
}

export enum _FormattedRolesEnum {
  'Super Admin' = 0,
  'Admin' = 1,
  'Driver' = 2,
  'Manager' = 3,
  'Scanner' = 13,
  'Vendor' = 14,
  'Camping Admin' = 15,
  'Camping Manager' = 16,
  'Vendor Staff' = 18,
  'Transport Manager' = 19,
  'Transport Dispatcher' = 20,
  'Camping Dispatcher' = 21,
  'Incident Manager' = 22,
  'Incident Dispatcher' = 23,
  'Service Manager' = 24,
  'Service Dispatcher' = 25,
  'Global Admin' = 26,
  'Global Manager' = 27,
  'Ontrack Manager' = 28,
  'Workforce Manager' = 29,
  'Operations Manager' = 30,
  'Camera Vendor' = 31,
  'Regional Manager' = 32,
  'Regional Admin' = 33,
  'Reference User' = 34,
  'Task Admin' = 35,
  'Legal Admin' = 36,
  'Dotmap Admin' = 37,
}

//Array to include global roles
export const GlobalRoles = [
  RolesNumberEnum.GLOBAL_ADMIN,
  RolesNumberEnum.GLOBAL_MANAGER,
  RolesNumberEnum.REGIONAL_ADMIN,
  RolesNumberEnum.REGIONAL_MANAGER,
];

//Array to include admin roles
export const AdminRoles = [
  RolesNumberEnum.ADMIN,
  RolesNumberEnum.OPERATIONS_MANAGER,
];

//Array to include admin roles
export const AdminRolesIncludedTaskAdmin = [
  RolesNumberEnum.ADMIN,
  RolesNumberEnum.OPERATIONS_MANAGER,
  RolesNumberEnum.TASK_ADMIN,
];

export const LegalModuleRoles = [
  RolesNumberEnum.SUPER_ADMIN,
  RolesNumberEnum.GLOBAL_ADMIN,
  RolesNumberEnum.LEGAL_ADMIN,
];
