"""license_plates

Revision ID: 04dcc11d6739
Revises: 73f5f6c633e0
Create Date: 2023-07-24 12:51:15.405730

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04dcc11d6739"
down_revision = "73f5f6c633e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license_plates",
        sa.Column("time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("license_plate", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("mac_address", sa.String(), nullable=False),
        sa.Column(
            "perception_stack_start_id",
            sa.String(),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("image_s3_path", sa.String(), nullable=False),
        sa.Column("thumbnail_s3_path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mac_address"], ["cameras.mac_address"], ondelete="CASCADE"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("license_plates")
    # ### end Alembic commands ###
