"""Add enforced rtsp url to camera

Revision ID: 051740001e29
Revises: 89b38f1fe214
Create Date: 2024-03-08 12:26:05.273319

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "051740001e29"
down_revision = "89b38f1fe214"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cameras", sa.Column("enforced_rtsp_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "enforced_rtsp_url")
    # ### end Alembic commands ###
