"""add per org webrtc

Revision ID: 0a5ac5f6677f
Revises: 9b20c359d0d0
Create Date: 2024-04-24 14:29:26.328494

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a5ac5f6677f"
down_revision = "9b20c359d0d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "organizations",
        sa.Column(
            "cameras_webrtc_settings",
            sa.String(),
            server_default=sa.text("'disabled'"),
            nullable=False,
        ),
    )
    # set all existing organizations to have webrtc manual
    op.execute("UPDATE organizations SET cameras_webrtc_settings = 'manual';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "cameras_webrtc_settings")
    # ### end Alembic commands ###
