"""Add images to FaceOccurrences

Revision ID: 17888fb7987a
Revises: fc4be6b984a7
Create Date: 2023-07-06 20:28:13.177255

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "17888fb7987a"
down_revision = "fc4be6b984a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "face_occurrences", sa.Column("face_s3_path", sa.String(), nullable=True)
    )
    op.add_column(
        "face_occurrences", sa.Column("person_s3_path", sa.String(), nullable=True)
    )
    op.add_column(
        "face_occurrences",
        sa.Column(
            "face_sharpness",
            sa.Float(),
            nullable=False,
            default=0.0,
            server_default="0.0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("face_occurrences", "face_sharpness")
    op.drop_column("face_occurrences", "person_s3_path")
    op.drop_column("face_occurrences", "face_s3_path")
    # ### end Alembic commands ###
