"""change always on default

Revision ID: 18522242d3a9
Revises: 41f970f2ddd8
Create Date: 2024-04-23 21:01:50.877278

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "18522242d3a9"
down_revision = "41f970f2ddd8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "alter table organizations alter column retention_hours_always_on_streams set"
        " default 1"
    )
    # update retention_hours_always_on_streams to 1 for all organizations
    op.execute("update organizations set retention_hours_always_on_streams = 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "alter table organizations alter column retention_hours_always_on_streams set"
        " default 168"
    )
    # ### end Alembic commands ###
