"""update_journey_request_table

Revision ID: 19ae4682582e
Revises: 813d76d71037
Create Date: 2023-08-24 04:52:49.647046

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19ae4682582e"
down_revision = "813d76d71037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    journey_request_status = sa.Enum(
        "INVALID", "PENDING", "NO_EMBEDDING", "SUCCESS", name="journeyrequeststatus"
    )
    # Create the enum type in the database
    journey_request_status.create(op.get_bind())

    op.add_column(
        "journey_requests",
        sa.Column("track_id", sa.Integer(), nullable=False, server_default="-1"),
    )
    op.add_column(
        "journey_requests",
        sa.Column(
            "perception_stack_start_id",
            sa.String(),
            nullable=False,
            server_default="unknown",
        ),
    )
    op.add_column(
        "journey_requests",
        sa.Column(
            "search_start_time",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "journey_requests",
        sa.Column(
            "search_end_time",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "journey_requests",
        sa.Column(
            "request_status",
            journey_request_status,
            nullable=False,
            server_default="INVALID",
        ),
    )
    op.drop_column("journey_requests", "object_min_y")
    op.drop_column("journey_requests", "object_max_y")
    op.drop_column("journey_requests", "object_min_x")
    op.drop_column("journey_requests", "object_max_x")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journey_requests",
        sa.Column(
            "object_max_x",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "journey_requests",
        sa.Column(
            "object_min_x",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "journey_requests",
        sa.Column(
            "object_max_y",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "journey_requests",
        sa.Column(
            "object_min_y",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("journey_requests", "request_status")
    op.drop_column("journey_requests", "search_end_time")
    op.drop_column("journey_requests", "search_start_time")
    op.drop_column("journey_requests", "perception_stack_start_id")
    op.drop_column("journey_requests", "track_id")
    sa.Enum(name="journeyrequeststatus").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
