"""add track_age

Revision ID: 21aa4e0fcc92
Revises: 8e469079c406
Create Date: 2023-05-05 10:22:34.434565

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21aa4e0fcc92"
down_revision = "8e469079c406"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "perception_object_events",
        sa.Column("track_age_s", sa.Float(), server_default="-1.0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("perception_object_events", "track_age_s")
    # ### end Alembic commands ###
