"""Remove alert enable flag for face alert

Revision ID: 296ec62bd4dd
Revises: a512ec1a4e77
Create Date: 2023-11-14 12:00:49.117622

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "296ec62bd4dd"
down_revision = "a512ec1a4e77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("face_alert_profiles", "alert_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "face_alert_profiles",
        sa.Column("alert_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
