"""add tenant to unprotected tables

Revision ID: 2b6a7c0cb402
Revises: d14b62940d91
Create Date: 2023-12-11 14:48:53.635300

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b6a7c0cb402"
down_revision = "d14b62940d91"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "cameras",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.execute(
        """
        UPDATE cameras SET tenant = locations.tenant FROM nvrs
        JOIN locations ON nvrs.location_id = locations.id
        WHERE cameras.nvr_uuid = nvrs.uuid
        """
    )
    op.create_foreign_key(
        "cameras_tenant_fkey", "cameras", "organizations", ["tenant"], ["tenant"]
    )
    op.add_column(
        "journey_requests",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.execute(
        """
        UPDATE journey_requests SET tenant = cameras.tenant FROM cameras
        WHERE journey_requests.mac_address = cameras.mac_address
        """
    )
    op.create_foreign_key(
        "journey_requests_tenant_fkey",
        "journey_requests",
        "organizations",
        ["tenant"],
        ["tenant"],
    )
    op.add_column(
        "license_plate_detections",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.execute(
        """
        UPDATE license_plate_detections SET tenant = cameras.tenant FROM cameras
        WHERE license_plate_detections.mac_address = cameras.mac_address
        """
    )
    op.create_foreign_key(
        "license_plate_detections_tenant_fkey",
        "license_plate_detections",
        "organizations",
        ["tenant"],
        ["tenant"],
    )
    # No foreign key here because it's huge and we will move it out later
    # no update because we will manually update it
    op.add_column(
        "mct_images",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.add_column(
        "nvrs",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.execute(
        """
        UPDATE nvrs SET tenant = locations.tenant FROM locations
        WHERE nvrs.location_id = locations.id
        """
    )
    op.create_foreign_key(
        "nvrs_tenant_fkey", "nvrs", "organizations", ["tenant"], ["tenant"]
    )
    # No foreign key here because it's huge and we will move it out later
    # no update because we will manually update it
    op.add_column(
        "perception_object_events",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    # No foreign key here because it's huge and we will move it out later
    # no update because we will manually update it
    op.add_column(
        "thumbnails",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.add_column(
        "unique_faces",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.execute(
        """
        UPDATE unique_faces SET tenant = nvrs.tenant FROM nvrs
        WHERE unique_faces.nvr_uuid = nvrs.uuid
        """
    )
    op.create_foreign_key(
        "unique_faces_tenant_fkey",
        "unique_faces",
        "organizations",
        ["tenant"],
        ["tenant"],
    )
    op.add_column(
        "user_alert_settings",
        sa.Column("tenant", sa.String(), server_default="unassigned", nullable=False),
    )
    op.execute(
        """
        UPDATE user_alert_settings SET tenant = cameras.tenant FROM cameras
        WHERE user_alert_settings.camera_mac_address = cameras.mac_address
        """
    )
    op.create_foreign_key(
        "user_alert_settings_tenant_fkey",
        "user_alert_settings",
        "organizations",
        ["tenant"],
        ["tenant"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_alert_settings_tenant_fkey", "user_alert_settings", type_="foreignkey"
    )
    op.drop_column("user_alert_settings", "tenant")
    op.drop_constraint("unique_faces_tenant_fkey", "unique_faces", type_="foreignkey")
    op.drop_column("unique_faces", "tenant")
    op.drop_column("thumbnails", "tenant")
    op.drop_column("perception_object_events", "tenant")
    op.drop_constraint("nvrs_tenant_fkey", "nvrs", type_="foreignkey")
    op.drop_column("nvrs", "tenant")
    op.drop_column("mct_images", "tenant")
    op.drop_constraint(
        "license_plate_detections_tenant_fkey",
        "license_plate_detections",
        type_="foreignkey",
    )
    op.drop_column("license_plate_detections", "tenant")
    op.drop_constraint(
        "journey_requests_tenant_fkey", "journey_requests", type_="foreignkey"
    )
    op.drop_column("journey_requests", "tenant")
    op.drop_constraint("cameras_tenant_fkey", "cameras", type_="foreignkey")
    op.drop_column("cameras", "tenant")
    # ### end Alembic commands ###
