"""Add column to store title of archive

Revision ID: 2bb192c48f2e
Revises: 776fe391a857
Create Date: 2023-10-25 17:58:06.532432

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bb192c48f2e"
down_revision = "776fe391a857"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archives", sa.Column("title", sa.String(), nullable=True))
    op.execute("UPDATE archives SET title = 'Placeholder Title'")
    op.alter_column("archives", "title", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archives", "title")
    # ### end Alembic commands ###
