"""Add scores to lpr table

Revision ID: 3357def83ce8
Revises: 2e108f71a78a
Create Date: 2023-08-08 16:04:38.941732

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3357def83ce8"
down_revision = "2e108f71a78a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "license_plates",
        sa.Column("dscore", sa.Float(), nullable=False, server_default=sa.text("1")),
    )
    op.add_column(
        "license_plates",
        sa.Column("vscore", sa.Float(), nullable=False, server_default=sa.text("1")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("license_plates", "vscore")
    op.drop_column("license_plates", "dscore")
    # ### end Alembic commands ###
