"""remove nvr name

Revision ID: 4162419bf4c1
Revises: 49e2b0e770df
Create Date: 2023-10-06 10:52:07.909775

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4162419bf4c1"
down_revision = "49e2b0e770df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nvrs", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nvrs", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
