"""Change vertical_flip to video_orientation_type

Revision ID: 493b01b0bd8b
Revises: 07a1f9ffb13d
Create Date: 2023-05-25 19:00:14.559840

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "493b01b0bd8b"
down_revision = "07a1f9ffb13d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    video_orientation_type = sa.Enum(
        "OrientationIdentity",
        "Orientation90R",
        "Orientation180",
        "Orientation90L",
        "OrientationHoriz",
        "OrientationVert",
        "OrientationUL_LR",
        "OrientationUR_LL",
        name="videoorientationtype",
    )
    # Create the enum type in the database
    video_orientation_type.create(op.get_bind())

    op.add_column(
        "cameras",
        sa.Column(
            "video_orientation_type",
            video_orientation_type,
            server_default="OrientationIdentity",
            nullable=False,
        ),
    )
    op.drop_column("cameras", "vertical_flip")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cameras",
        sa.Column(
            "vertical_flip",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("cameras", "video_orientation_type")
    sa.Enum(name="videoorientationtype").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
