"""add num_cameras_slots to nvr

Revision ID: 49e2b0e770df
Revises: d382bd2dbadd
Create Date: 2023-10-06 15:18:44.594080

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49e2b0e770df"
down_revision = "d382bd2dbadd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "nvrs",
        sa.Column(
            "max_cameras_slots",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("16"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nvrs", "max_cameras_slots")
    # ### end Alembic commands ###
