"""add always streaming flag

Revision ID: 6205c0cf6cae
Revises: 13b8ad274ffe
Create Date: 2023-06-22 14:12:35.206227

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6205c0cf6cae"
down_revision = "13b8ad274ffe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "cameras",
        sa.Column(
            "is_always_streaming",
            sa.Boolean(),
            nullable=False,
            default=False,
            server_default="false",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "is_always_streaming")
    # ### end Alembic commands ###
