"""delete stream availabilities

Revision ID: 620fc65a5a97
Revises: 31fb0e182981
Create Date: 2023-04-26 11:04:13.147521

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "620fc65a5a97"
down_revision = "31fb0e182981"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stream_data_availabilities")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream_data_availabilities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("camera_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "start_timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "availability_duration_s", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name="stream_data_availabilities_camera_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="stream_data_availabilities_pkey"),
    )
    # ### end Alembic commands ###
