"""add retention for alwayson stream per org

Revision ID: 702f1a0f7790
Revises: be46ce578090
Create Date: 2023-09-20 22:53:09.235984

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "702f1a0f7790"
down_revision = "be46ce578090"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "retention_hours_always_on_streams",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("168"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "retention_hours_always_on_streams")
    # ### end Alembic commands ###
