"""remove legacy fields shared video

Revision ID: 798eaaa21eb1
Revises: 19ae4682582e
Create Date: 2023-08-23 14:03:01.867656

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "798eaaa21eb1"
down_revision = "19ae4682582e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shared_videos", "live_stream_name")
    op.drop_column("shared_videos", "end_time")
    op.drop_column("shared_videos", "start_time")
    op.drop_column("shared_videos", "mac_address")
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(@lberg): I've set defaults here as the columns were not nullable
    op.add_column(
        "shared_videos",
        sa.Column(
            "mac_address",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "shared_videos",
        sa.Column(
            "start_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "shared_videos",
        sa.Column(
            "end_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "shared_videos",
        sa.Column(
            "live_stream_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###
