"""augment clipdata for long_video_download

Revision ID: 80178610c5a9
Revises: d50f27a93379
Create Date: 2023-05-12 11:37:56.282445

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80178610c5a9"
down_revision = "d50f27a93379"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clips_data", sa.Column("kvs_stream_name", sa.String(), nullable=True)
    )
    op.add_column("clips_data", sa.Column("s3_path", sa.String(), nullable=True))
    op.add_column(
        "clips_data",
        sa.Column("expiration_time", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column("shared_videos", sa.Column("clip_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        "shared_videos_clip_id_fkey",
        "shared_videos",
        "clips_data",
        ["clip_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "shared_videos_clip_id_fkey", "shared_videos", type_="foreignkey"
    )
    op.drop_column("shared_videos", "clip_id")
    op.drop_column("clips_data", "expiration_time")
    op.drop_column("clips_data", "s3_path")
    op.drop_column("clips_data", "kvs_stream_name")
    # ### end Alembic commands ###
