"""Add idx_in_frame to FaceOccurrence

Revision ID: 80f94c145690
Revises: 80c5c562053f
Create Date: 2024-03-27 23:24:22.102137

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80f94c145690"
down_revision = "80c5c562053f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "face_occurrences", sa.Column("pcp_idx_in_frame", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("face_occurrences", "pcp_idx_in_frame")
    # ### end Alembic commands ###
