"""Add face related tables

Revision ID: 813f682f8806
Revises: e11ddc590f3c
Create Date: 2023-05-31 23:43:16.376585

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "813f682f8806"
down_revision = "e11ddc590f3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unique_faces",
        sa.Column("unique_face_id", sa.String(), nullable=False),
        sa.Column("nvr_uuid", sa.String(), nullable=False),
        sa.Column("s3_path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["nvr_uuid"], ["nvrs.uuid"]),
        sa.PrimaryKeyConstraint("unique_face_id", "nvr_uuid"),
    )
    op.create_table(
        "face_occurrences",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("unique_face_id", sa.String(), nullable=False),
        sa.Column("nvr_uuid", sa.String(), nullable=False),
        sa.Column("mac_address", sa.String(), nullable=False),
        sa.Column("occurrence_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["nvr_uuid"], ["nvrs.uuid"]),
        sa.ForeignKeyConstraint(
            ["mac_address"], ["cameras.mac_address"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unique_face_id", "nvr_uuid"],
            ["unique_faces.unique_face_id", "unique_faces.nvr_uuid"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("face_occurrences")
    op.drop_table("unique_faces")
    # ### end Alembic commands ###
