"""remove the clip optionality from shared videos

Revision ID: 8457265657b7
Revises: 4ca4e816471b
Create Date: 2023-09-07 14:49:01.073447

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8457265657b7"
down_revision = "4ca4e816471b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shared_videos", "clip_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shared_videos", "clip_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###
