"""Last alert sent columns

Revision ID: 86c77313b668
Revises: df08d0c72086
Create Date: 2023-03-16 16:36:05.742836

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86c77313b668"
down_revision = "0e4f2d2de4b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cameras",
        sa.Column("last_alert_time", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "nvrs", sa.Column("last_alert_time", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nvrs", "last_alert_time")
    op.drop_column("cameras", "last_alert_time")
    # ### end Alembic commands ###
