"""updating logs action column to be enum

Revision ID: 8b6243a5fe2b
Revises: cc05d5d22b28
Create Date: 2023-10-11 23:05:19.098321

"""

import sqlalchemy as sa
from alembic import op

from backend.access_logs.constants import UserActions

# revision identifiers, used by Alembic.
revision = "8b6243a5fe2b"
down_revision = "cc05d5d22b28"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_logs")
    op.create_table(
        "access_logs",
        sa.Column("tenant", sa.String(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "action",
            sa.Enum(*[x.name for x in UserActions], name="useraction"),
            nullable=False,
        ),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["tenant"], ["organizations.tenant"]),
        sa.PrimaryKeyConstraint(
            "tenant",
            "action",
            "user_email",
            "ip_address",
            "timestamp",
            name="access_logs_pkey",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("access_logs")
    user_action = sa.Enum(*[x.name for x in UserActions], name="useraction")
    user_action.drop(op.get_bind())
    op.create_table(
        "access_logs",
        sa.Column("tenant", sa.String(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["tenant"], ["organizations.tenant"]),
        sa.PrimaryKeyConstraint(
            "tenant",
            "action",
            "user_email",
            "ip_address",
            "timestamp",
            name="access_logs_pkey",
        ),
    )

    # ### end Alembic commands ###
