"""add archive table

Revision ID: 8e469079c406
Revises: e9a0b282a6b0
Create Date: 2023-05-03 11:09:38.578414

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e469079c406"
down_revision = "e9a0b282a6b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archives",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_user_email", sa.String(), nullable=False),
        sa.Column("tenant", sa.String(), nullable=False),
        sa.Column("creation_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["tenant"], ["organizations.tenant"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shared_archives",
        sa.Column("archive_id", sa.Integer(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["archive_id"], ["archives.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("archive_id", "user_email"),
    )
    op.create_table(
        "clips_data",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("mac_address", sa.String(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("creation_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mac_address"], ["cameras.mac_address"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mac_address", "start_time", "end_time"),
    )
    op.create_table(
        "clips_to_archives",
        sa.Column("clip_id", sa.BigInteger(), nullable=False),
        sa.Column("archive_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["archive_id"], ["archives.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["clip_id"], ["clips_data.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("clip_id", "archive_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clips_to_archives")
    op.drop_table("clips_data")
    op.drop_table("shared_archives")
    op.drop_table("archives")
    # ### end Alembic commands ###
