"""add mct versioning

Revision ID: 9b20c359d0d0
Revises: 18522242d3a9
Create Date: 2024-04-23 23:55:16.250632

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9b20c359d0d0"
down_revision = "18522242d3a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "embedding_responses", sa.Column("clip_version", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embedding_responses", "clip_version")
    # ### end Alembic commands ###
