"""add perception stack start ID

Revision ID: 9eee1791e6a7
Revises: 21aa4e0fcc92
Create Date: 2023-05-09 17:03:48.080130

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9eee1791e6a7"
down_revision = "21aa4e0fcc92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "perception_object_events",
        sa.Column(
            "perception_stack_start_id",
            sa.String(),
            server_default="unknown",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("perception_object_events", "perception_stack_start_id")
    # ### end Alembic commands ###
