"""Add low_res_bitrate_kbps to organization

Revision ID: a512ec1a4e77
Revises: 0e50ff0af31b
Create Date: 2023-11-13 19:17:56.558591

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a512ec1a4e77"
down_revision = "0e50ff0af31b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "low_res_bitrate_kbps",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("512"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "low_res_bitrate_kbps")
    # ### end Alembic commands ###
