"""Add face alert profile table

Revision ID: ae8fca5598c2
Revises: 4162419bf4c1
Create Date: 2023-10-09 15:06:39.534941

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae8fca5598c2"
down_revision = "4162419bf4c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "face_alert_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_person_of_interest", sa.Boolean(), nullable=False),
        sa.Column("alert_enabled", sa.Boolean(), nullable=False),
        sa.Column("owner_user_email", sa.String(), nullable=False),
        sa.Column("creation_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("face_s3_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["tenant"], ["organizations.tenant"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "unique_faces_to_alert_profiles",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("unique_face_id", sa.String(), nullable=False),
        sa.Column("nvr_uuid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["face_alert_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["unique_face_id", "nvr_uuid"],
            ["unique_faces.unique_face_id", "unique_faces.nvr_uuid"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("unique_face_id", "nvr_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unique_faces_to_alert_profiles")
    op.drop_table("face_alert_profiles")
    # ### end Alembic commands ###
