"""add column to store when clip was linked to archive

Revision ID: bc589465f094
Revises: 2bb192c48f2e
Create Date: 2023-10-30 22:48:39.005926

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc589465f094"
down_revision = "2bb192c48f2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clips_to_archives",
        sa.Column("creation_time", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.execute("UPDATE clips_to_archives SET creation_time = NOW()")
    op.alter_column("clips_to_archives", "creation_time", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clips_to_archives", "creation_time")
    # ### end Alembic commands ###
