"""text_query_response_id_not_index

Revision ID: cbba0ec98c56
Revises: 29282da60850
Create Date: 2023-04-15 04:04:31.187391

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "cbba0ec98c56"
down_revision = "29282da60850"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_text_search_response_id", table_name="text_search_response")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_text_search_response_id", "text_search_response", ["id"], unique=False
    )
    # ### end Alembic commands ###
