"""Add Kiosk related tables

Revision ID: cc05d5d22b28
Revises: 7c965a3cbcb2
Create Date: 2023-10-11 00:11:19.552621

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc05d5d22b28"
down_revision = "7c965a3cbcb2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kiosks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("rotate_frequency_s", sa.Float(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("creator_user_email", sa.String(), nullable=False),
        sa.Column("creation_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
        sa.UniqueConstraint("name", "organization_id"),
    )
    op.create_table(
        "kiosk_walls",
        sa.Column("kiosk_id", sa.Integer(), nullable=False),
        sa.Column("wall_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["kiosk_id"], ["kiosks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wall_id"], ["walls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("kiosk_id", "wall_id"),
        sa.UniqueConstraint("kiosk_id", "index"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kiosk_walls")
    op.drop_table("kiosks")
    # ### end Alembic commands ###
