"""Add Timezone to Location

Revision ID: d14b62940d91
Revises: b3070ad6eb01
Create Date: 2023-12-15 13:00:41.048809

"""

import sqlalchemy as sa
from alembic import op

from backend.access_logs.constants import UserActions
from backend.database.migration_utils import TableColumnPair, change_enum_values

# revision identifiers, used by Alembic.
revision = "d14b62940d91"
down_revision = "b3070ad6eb01"
branch_labels = None
depends_on = None

OLD_ACTION_NAME_VALUES = [
    x.name
    for x in UserActions
    if x.name
    not in ("UPDATED_LOCATION_TIMEZONE", "UPDATED_LOCATION_ENABLE_SETTING_TIMEZONE")
]

NEW_ACTION_NAME_VALUES = [x.name for x in UserActions]

TABLE_COLUMN_PAIRS = [TableColumnPair("access_logs", "action")]

ENUM_NAME = "useraction"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "timezone",
            sa.String(),
            server_default="America/Los_Angeles",
            nullable=False,
        ),
    )
    op.add_column(
        "locations",
        sa.Column(
            "enable_setting_timezone",
            sa.Boolean,
            server_default=sa.false(),
            nullable=False,
        ),
    )
    # Update the timezone in locations with the timezone of an associated NVR
    op.execute(
        """
        UPDATE locations
        SET timezone = (
            SELECT timezone
            FROM nvrs
            WHERE nvrs.location_id = locations.id
            LIMIT 1
        )
        WHERE EXISTS (
            SELECT 1
            FROM nvrs
            WHERE nvrs.location_id = locations.id
        );
    """
    )
    change_enum_values(
        table_column_pairs=TABLE_COLUMN_PAIRS,
        enum_name=ENUM_NAME,
        current_values=set(OLD_ACTION_NAME_VALUES),
        new_values=set(NEW_ACTION_NAME_VALUES),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    DELETE FROM access_logs
    WHERE action in (
    'UPDATED_LOCATION_TIMEZONE', 'UPDATED_LOCATION_ENABLE_SETTING_TIMEZONE'
    );
    """
    )
    change_enum_values(
        table_column_pairs=TABLE_COLUMN_PAIRS,
        enum_name=ENUM_NAME,
        current_values=set(NEW_ACTION_NAME_VALUES),
        new_values=set(OLD_ACTION_NAME_VALUES),
    )

    op.drop_column("locations", "enable_setting_timezone")
    op.drop_column("locations", "timezone")
    # ### end Alembic commands ###
