"""add username and password to camera

Revision ID: d1c69e4fc395
Revises: d75537596d35
Create Date: 2023-04-17 14:19:35.524007

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1c69e4fc395"
down_revision = "d75537596d35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cameras", sa.Column("username", sa.String(), nullable=True))
    op.add_column("cameras", sa.Column("password", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "password")
    op.drop_column("cameras", "username")
    # ### end Alembic commands ###
