"""add vertical flip to camera

Revision ID: d50f27a93379
Revises: 9eee1791e6a7
Create Date: 2023-05-11 12:44:26.115728

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d50f27a93379"
down_revision = "9eee1791e6a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "cameras",
        sa.Column(
            "vertical_flip", sa.Boolean(), nullable=False, server_default="False"
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "vertical_flip")
    # ### end Alembic commands ###
