"""Add composite index for face occurrence

Revision ID: d6028c9c04b2
Revises: 663a64047cfa
Create Date: 2024-01-15 15:12:13.305212

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d6028c9c04b2"
down_revision = "663a64047cfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "face_occurrence_time_mac_address_unique_face_id_idx",
        "face_occurrences",
        ["unique_face_id", "mac_address", "occurrence_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "face_occurrence_time_mac_address_unique_face_id_idx",
        table_name="face_occurrences",
    )
    # ### end Alembic commands ###
