"""add new column last_seen to camera

Revision ID: df08d0c72086
Revises: e512f75fc776
Create Date: 2023-03-09 17:30:39.327228

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df08d0c72086"
down_revision = "2ab1a187783a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cameras",
        sa.Column("last_seen_time", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.drop_column("cameras", "last_discovery_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "last_seen_time")
    op.add_column(
        "cameras",
        sa.Column(
            "last_discovery_time",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    # ### end Alembic commands ###
