"""Add idling alert config to UserAlertSetting table

Revision ID: e9a0b282a6b0
Revises: 620fc65a5a97
Create Date: 2023-05-02 18:16:41.692522

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9a0b282a6b0"
down_revision = "620fc65a5a97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_alert_settings",
        sa.Column("min_idle_duration_s", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_alert_settings", "min_idle_duration_s")
    # ### end Alembic commands ###
