"""Brivo Integration, allow clients to use their API keys.

Revision ID: eea538bf4213
Revises: 96489688a63f
Create Date: 2024-01-05 15:56:43.629138

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eea538bf4213"
down_revision = "96489688a63f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brivo_tokens", sa.Column("api_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("brivo_tokens", "api_key")
    # ### end Alembic commands ###
