import enum


class AlertType(str, enum.Enum):
    """Alert type."""

    TASK_FAILED = "TASK_FAILED"
    NVR_DOWN = "NVR_DOWN"
    NVR_UP = "NVR_UP"
    BACKEND_DOWN = "BACKEND_DOWN"
    BACKEND_THUMBNAILS_DOWN = "BACKEND_THUMBNAILS_DOWN"
    FRONTEND_LIVE_STREAM_DOWN = "FRONTEND_LIVE_STREAM_DOWN"
    FRONTEND_CLIP_DOWN = "FRONTEND_CLIP_DOWN"
    EDGE_CAMERA_ALERT = "EDGE_CAMERA_ALERT"
    EDGE_NVR_ALERT = "EDGE_NVR_ALERT"
    CAMERA_DOWN = "CAMERA_DOWN"
    CAMERA_UP = "CAMERA_UP"
    MOST_CAMERAS_DOWN = "MOST_CAMERAS_DOWN"
    ARCHIVE_CLIP_UPLOAD_FAILED = "ARCHIVE_CLIP_UPLOAD_FAILED"
    RETENTION_ENFORCEMENT_TASK_FAILED = "RETENTION_ENFORCEMENT_TASK_FAILED"
    RETENTION_ENFORCEMENT_RESOURCE_FAILED = "RETENTION_ENFORCEMENT_RESOURCE_FAILED"
    PARTITION_TASK_FAILED = "PARTITION_TASK_FAILED"
    TEXT_SEARCH_NVR_FAILED = "TEXT_SEARCH_NVR_FAILED"
    JOURNEY_MULTIPLE_TRACKS_FOUND = "JOURNEY_MULTIPLE_TRACKS_FOUND"
    DUPLICATED_OBJECT_DETECTIONS = "DUPLICATED_OBJECT_DETECTIONS"
    MEMBER_NOTIFY_FAILED = "MEMBER_NOTIFY_FAILED"
    ALERTS_NOTIFICATION_FAILED = "ALERTS_NOTIFICATION_FAILED"
    NOTIFICATION_TASK_FAILED = "NOTIFICATION_TASK_FAILED"
    EXCEED_NUMBER_OF_LICENSED_CAMERAS_IN_ORGANIZATION = (
        "EXCEED_NUMBER_OF_LICENSED_CAMERAS_IN_ORGANIZATION"
    )
    FACE_UPLOAD_NVR_PROCESS_FAILED = "FACE_UPLOAD_NVR_PROCESS_FAILED"


class CameraPipelineAlertType(str, enum.Enum):
    """Camera pipeline alert type."""

    CAMERA_DISCOVERY_FAILURE = "CameraDiscoveryFailure"
    ONVIF_CONNECTION_FAILED = "OnvifConnectionFailed"
    ONVIF_INVALID_CREDENTIALS = "OnvifInvalidCredentials"
    ONVIF_OTHER_ERROR = "OnvifOtherError"
    ONVIF_TIMED_OUT = "OnvifTimedOut"
    PRODUCER_NO_PROFILE_FOUND = "ProducerNoProfileFound"
    PRODUCER_CONNECTION_FAILED = "ProducerConnectionFailed"
    PRODUCER_INVALID_CREDENTIALS = "ProducerInvalidCredentials"
    PRODUCER_RTSP_CONNECTION_ERROR = "ProducerRtspConnectionError"
    PRODUCER_CAMERA_IDLE = "ProducerCameraIdle"
    PRODUCER_HIGH_FPS = "ProducerHighFps"


class EdgeStatusUpdateType(str, enum.Enum):
    """Edge status update type."""

    NVR_KVS_CONNECTION_FAILURE = "KvsConnectionFailure"
