export const EXCEPTIONS = {
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_OR_PASSWORD_INCORRECT: "EMAIL_OR_PASSWORD_INCORRECT",
  USER_EMAIL_NOT_VERIFIED: "USER_EMAIL_NOT_VERIFIED",
  ALREADY_HAS_A_COMPANY: "ALREADY_HAS_A_COMPANY",
  WRONG_TOKEN: "WRONG_TOKEN",
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
  COMPANY_ALREADY_EXISTS: "COMPANY_ALREADY_EXISTS",
  COMPANY_EMAIL_NOT_VERIFIED: "COMPANY_EMAIL_NOT_VERIFIED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  FORGOT_PASSWORD_TOKEN_EXPIRED: "FORGOT_PASSWORD_TOKEN_EXPIRED",
  USER_HAS_ALREADY_SIGNED_UP: "USER_HAS_ALREADY_SIGNED_UP",
  MANAGER_CAN_ONLY_INVITE_BIDDERS: "MANAGER_CAN_ONLY_INVITE_BIDDERS",
  COPMANY_ADMIN_CAN_ONLY_INVITE_MANAGER_AND_BIDDER: "COPMANY_ADMIN_CAN_ONLY_INVITE_MANAGER_AND_BIDDER",
  MANAGER_CAN_ONLY_UPDATE_BIDDERS_INVITE: "MANAGER_CAN_ONLY_UPDATE_BIDDERS_INVITE",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_ALREADY_ACCEPTED: "INVITATION_ALREADY_ACCEPTED",
  ALREADY_HAVE_A_PROFILE: "ALREADY_HAVE_A_PROFILE",
  CANNOT_ADD_MEMBER_TO_JUST_ME: "CANNOT_ADD_MEMBER_TO_JUST_ME",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  JOB_ALREADY_EXISTS: "JOB_ALREADY_EXISTS",
  BID_ALREADY_EXISTS: "BID_ALREADY_EXISTS",
  RESPONSE_NOT_TRUE: "RESPONSE_NOT_TRUE",
  TAG_ALREADY_EXISTS: "TAG_ALREADY_EXISTS",
  BID_NOT_FOUND: "BID_NOT_FOUND",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  TAGS_NOT_FOUND: "TAGS_NOT_FOUND",
  PORTFOLIO_ALREADY_EXISTS: "PORTFOLIO_ALREADY_EXISTS",
  PORTFOLIO_NOT_FOUND: "PORTFOLIO_NOT_FOUND",
  PORTFOLIOS_NOT_FOUND: "PORTFOLIOS_NOT_FOUND",
  LINKS_ALREADY_EXIST: "LINKS_ALREADY_EXIST",
  LINKS_NOT_FOUND: "LINKS_NOT_FOUND",
  DUPLICATE_LINKS: "DUPLICATE_LINKS",
  TEMPLATE_ALREADY_EXISTS: "TEMPLATE_ALREADY_EXISTS",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  SETTINGS_NOT_FOUND: "SETTINGS_NOT_FOUND",
  SETTINGS_ALREADY_EXISTS: "SETTINGS_ALREADY_EXISTS",
  COMPANY_OWNER_CANNOT_BE_UPDATED: "COMPANY_OWNER_CANNOT_BE_UPDATED",
  COMPANY_OWNER_CANNOT_BE_DELETED: "COMPANY_OWNER_CANNOT_BE_DELETED",
};

export const INVALID_SESSION = 'Invalid session.';
export const INVALID_ROLE = 'Access denied for this role.';
export const USER_NOT_FOUND = 'User not found!';
export const MAINTENANCE = 'MAINTENANCE_MODE';
export const PAYMENT_REQUIRED_OWNER = 'Your subscription has expired. Please update your payment information to restore access to Restat.';
export const PAYMENT_REQUIRED_ALL = 'There seems to be an issue with the payment. Please contact the account owner in your organization to restore access to your account.';

