import { Event } from '@ontrack-tech-group/common/models';
import {
  RolesEnum,
  RolesNumberEnum,
} from '@ontrack-tech-group/common/constants';
export * from './responses';
export * from './enums';
export * from './interfaces';

export const generalRoleConditions = {
  [RolesNumberEnum.OPERATIONS_MANAGER]: [0, 28, 1, 26, 27, 32, 33],
  [RolesNumberEnum.ADMIN]: [0, 28, 26, 27, 32, 33],
  [RolesNumberEnum.REGIONAL_MANAGER]: [0, 28, 26, 27, 33],
  [RolesNumberEnum.REGIONAL_ADMIN]: [0, 28, 26, 27],
  [RolesNumberEnum.GLOBAL_MANAGER]: [0, 28, 26, 27],
  [RolesNumberEnum.GLOBAL_ADMIN]: [0, 28],
  [RolesNumberEnum.ONTRACK_MANAGER]: [0],
  [RolesNumberEnum.SUPER_ADMIN]: [],
};

// For mention in event plan
export const generalRoleConditionsForMention = {
  [RolesNumberEnum.OPERATIONS_MANAGER]: [0, 28, 26, 27, 32, 33],
  [RolesNumberEnum.ADMIN]: [0, 28],
  [RolesNumberEnum.REGIONAL_MANAGER]: [0, 28, 26, 27, 33],
  [RolesNumberEnum.REGIONAL_ADMIN]: [0, 28, 26, 27],
  [RolesNumberEnum.GLOBAL_MANAGER]: [0, 28, 26, 27],
  [RolesNumberEnum.GLOBAL_ADMIN]: [0, 28],
  [RolesNumberEnum.ONTRACK_MANAGER]: [0],
  [RolesNumberEnum.SUPER_ADMIN]: [],
};

export const workforceRoleConditions = {
  [RolesNumberEnum.OPERATIONS_MANAGER]: [0, 28, 26, 27, 2, 32, 33, 36],
  [RolesNumberEnum.ADMIN]: [0, 28, 26, 27, 2, 32, 33, 36],
  [RolesNumberEnum.REGIONAL_ADMIN]: [0, 28, 26, 27, 2, 32, 33, 36],
  [RolesNumberEnum.REGIONAL_MANAGER]: [0, 28, 26, 2, 27, 32, 33, 36],
  [RolesNumberEnum.GLOBAL_MANAGER]: [0, 28, 26, 2, 27, 32, 33, 36],
  [RolesNumberEnum.GLOBAL_ADMIN]: [0, 28, 2, 26, 27, 32, 33, 36],
  [RolesNumberEnum.ONTRACK_MANAGER]: [0, 2, 28, 26, 27, 32, 33, 36],
  [RolesNumberEnum.SUPER_ADMIN]: [0, 2, 28, 26, 27, 32, 33, 36],
};

export const generalRoleConditionsString = {
  [RolesNumberEnum.OPERATIONS_MANAGER]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
  [RolesNumberEnum.ADMIN]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
  [RolesNumberEnum.REGIONAL_ADMIN]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
  [RolesNumberEnum.REGIONAL_MANAGER]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
  [RolesNumberEnum.GLOBAL_MANAGER]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
  [RolesNumberEnum.GLOBAL_ADMIN]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
  [RolesNumberEnum.ONTRACK_MANAGER]: [
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.SUPER_ADMIN,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
  [RolesNumberEnum.SUPER_ADMIN]: [
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.SUPER_ADMIN,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
  ],
};

export const moduleRoleMapping = {
  staff_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
  ],
  incident_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.INCIDENT_DISPATCHER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.TRANSPORT_MANAGER,
    RolesEnum.TRANSPORT_DISPATCHER,
    RolesEnum.DRIVER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.SERVICE_MANAGER,
    RolesEnum.SERVICE_DISPATCHER,
  ],
  incident_future_v2: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.INCIDENT_DISPATCHER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.TRANSPORT_MANAGER,
    RolesEnum.TRANSPORT_DISPATCHER,
    RolesEnum.DRIVER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.SERVICE_MANAGER,
    RolesEnum.SERVICE_DISPATCHER,
  ],
  camping_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
  ],
  service_request_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.SERVICE_MANAGER,
    RolesEnum.SERVICE_DISPATCHER,
  ],
  message_service: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_ADMIN,
  ],
  transportation_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.TRANSPORT_MANAGER,
    RolesEnum.TRANSPORT_DISPATCHER,
  ],
  inventory_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
  ],
  task_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.TASK_ADMIN,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.INCIDENT_DISPATCHER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
  ],
  ticket_clear_template_future: [RolesEnum.SUPER_ADMIN],

  event_form_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
  ],

  dot_map_service: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.DOTMAP_ADMIN,
  ],

  dot_map_service_v2: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.DOTMAP_ADMIN,
  ],
  audit_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
  ],
  reporting_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.ADMIN,
  ],
};

// for listing of roles in Staff Listing
export const rolesConditions = {
  [RolesNumberEnum.OPERATIONS_MANAGER]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.TASK_ADMIN,
    RolesEnum.DOTMAP_ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
  [RolesNumberEnum.ADMIN]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
  [RolesNumberEnum.REGIONAL_MANAGER]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
  [RolesNumberEnum.REGIONAL_ADMIN]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
  [RolesNumberEnum.GLOBAL_MANAGER]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
  [RolesNumberEnum.GLOBAL_ADMIN]: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
  [RolesNumberEnum.ONTRACK_MANAGER]: [
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.SUPER_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
  [RolesNumberEnum.SUPER_ADMIN]: [
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.SUPER_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.DRIVER,
    RolesEnum.VENDOR,
    RolesEnum.VENDOR_STAFF,
    RolesEnum.SCANNER,
    RolesEnum.MANAGER,
  ],
};

export const excludeArray: string[] = [
  RolesEnum.SUPER_ADMIN,
  RolesEnum.ONTRACK_MANAGER,
  RolesEnum.GLOBAL_ADMIN,
  RolesEnum.GLOBAL_MANAGER,
  RolesEnum.REGIONAL_MANAGER,
  RolesEnum.REGIONAL_ADMIN,
  RolesEnum.ADMIN,
  RolesEnum.TASK_ADMIN,
  RolesEnum.DOTMAP_ADMIN,
  RolesEnum.OPERATIONS_MANAGER,
  RolesEnum.WORKFORCE_MANAGER,
  RolesEnum.CAMERA_VENDOR,
  RolesEnum.DRIVER,
  RolesEnum.VENDOR,
  RolesEnum.VENDOR_STAFF,
  RolesEnum.SCANNER,
  RolesEnum.MANAGER,
];

export const accessibleModules = {
  transportation_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.TRANSPORT_MANAGER,
    RolesEnum.TRANSPORT_DISPATCHER,
    RolesEnum.DRIVER,
  ],
  workforce_messaging: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
  ],
  service_request_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.SERVICE_MANAGER,
    RolesEnum.SERVICE_DISPATCHER,
  ],
  message_service: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_ADMIN,
  ],
  lost_and_found_future: false,
  inventory_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
  ],
  incident_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.INCIDENT_DISPATCHER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.TRANSPORT_MANAGER,
    RolesEnum.TRANSPORT_DISPATCHER,
    RolesEnum.DRIVER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.SERVICE_MANAGER,
    RolesEnum.SERVICE_DISPATCHER,
  ],
  incident_future_v2: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.INCIDENT_DISPATCHER,
    RolesEnum.CAMERA_VENDOR,
    RolesEnum.TRANSPORT_MANAGER,
    RolesEnum.TRANSPORT_DISPATCHER,
    RolesEnum.DRIVER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
    RolesEnum.SERVICE_MANAGER,
    RolesEnum.SERVICE_DISPATCHER,
  ],
  dot_map_service: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.DOTMAP_ADMIN,
  ],
  dot_map_service_v2: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.DOTMAP_ADMIN,
  ],
  camping_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
  ],
  task_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.TASK_ADMIN,
    RolesEnum.INCIDENT_MANAGER,
    RolesEnum.INCIDENT_DISPATCHER,
    RolesEnum.CAMPING_MANAGER,
    RolesEnum.CAMPING_DISPATCHER,
    RolesEnum.CAMPING_ADMIN,
    RolesEnum.WORKFORCE_MANAGER,
  ],
  ticket_clear_template_future: [RolesEnum.SUPER_ADMIN],
  event_form_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.GLOBAL_ADMIN,
    RolesEnum.GLOBAL_MANAGER,
    RolesEnum.REGIONAL_ADMIN,
    RolesEnum.ADMIN,
    RolesEnum.OPERATIONS_MANAGER,
    RolesEnum.INCIDENT_MANAGER,
  ],
  reporting_future: [
    RolesEnum.SUPER_ADMIN,
    RolesEnum.ONTRACK_MANAGER,
    RolesEnum.ADMIN,
  ],
};

// Define role groups with their corresponding event properties
export const roleEventMapping = (event: Event) => {
  return {
    incident: {
      roles: ['incident_manager', 'incident_dispatcher', 'camera_vendor'],
      eventProperty: event.incident_future
        ? 'incident_future'
        : 'incident_future_v2',
    },
    camping: {
      roles: [
        'camping_manager',
        'camping_dispatcher',
        'camping_admin',
        'camping_staff',
      ],
      eventProperty: 'camping_future',
    },
    service: {
      roles: ['service_manager', 'service_dispatcher'],
      eventProperty: 'service_request_future',
    },
    transportation: {
      roles: [
        'transport_manager',
        'transport_dispatcher',
        'manager',
        'scanner',
        'driver',
      ],
      eventProperty: 'transportation_future',
    },
  };
};

export const mailChimpUserRoles = [
  RolesEnum.GLOBAL_ADMIN,
  RolesEnum.GLOBAL_MANAGER,
  RolesEnum.REGIONAL_ADMIN,
  RolesEnum.REGIONAL_MANAGER,
  RolesEnum.ADMIN,
  RolesEnum.OPERATIONS_MANAGER,
  RolesEnum.INCIDENT_MANAGER,
];

export const userScanType = [37, 38, 40, 41, 42, 33];
