# Max number of objects S3 allows to delete in a single request
S3_BATCH_DELETE_LIMIT = 1000

# Per camera delete limits for each resource type
PER_CAMERA_DELETE_LIMIT_THUMBNAILS = 10000
PER_CAMERA_DELETE_LIMIT_MCT_IMAGES = 4000
PER_CAMERA_DELETE_LIMIT_FACE_OCCURRENCES = 20000
PER_CAMERA_DELETE_LIMIT_LICENSE_PLATE_DETECTION = 2000
