const countries = [
  { "name": "Afghanistan", "code": "AF", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1eb.svg" },
  { "name": "Åland Islands", "code": "AX", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1fd.svg" },
  { "name": "Albania", "code": "AL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1f1.svg" },
  { "name": "Algeria", "code": "DZ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e9-1f1ff.svg" },
  { "name": "American Samoa", "code": "AS", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1f8.svg" },
  { "name": "AndorrA", "code": "AD" },
  { "name": "Angola", "code": "AO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1f4.svg" },
  { "name": "Anguilla", "code": "AI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1ee.svg" },
  { "name": "Antarctica", "code": "AQ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1f6.svg" },
  { "name": "Antigua and Barbuda", "code": "AG" },
  { "name": "Argentina", "code": "AR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1f7.svg" },
  { "name": "Armenia", "code": "AM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1f2.svg" },
  { "name": "Aruba", "code": "AW", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1fc.svg" },
  { "name": "Australia", "code": "AU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1fa.svg" },
  { "name": "Austria", "code": "AT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1f9.svg" },
  { "name": "Azerbaijan", "code": "AZ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1ff.svg" },
  { "name": "Bahamas", "code": "BS", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1f8.svg" },
  { "name": "Bahrain", "code": "BH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1ed.svg" },
  { "name": "Bangladesh", "code": "BD", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1e9.svg" },
  { "name": "Barbados", "code": "BB", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1e7.svg" },
  { "name": "Belarus", "code": "BY", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1fe.svg" },
  { "name": "Belgium", "code": "BE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1ea.svg" },
  { "name": "Belize", "code": "BZ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1ff.svg" },
  { "name": "Benin", "code": "BJ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1ef.svg" },
  { "name": "Bermuda", "code": "BM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1f2.svg" },
  { "name": "Bhutan", "code": "BT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1f9.svg" },
  { "name": "Bolivia", "code": "BO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1f4.svg" },
  { "name": "Bosnia and Herzegovina", "code": "BA" },
  { "name": "Botswana", "code": "BW", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1fc.svg" },
  { "name": "Bouvet Island", "code": "BV", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1fb.svg" },
  { "name": "Brazil", "code": "BR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1f7.svg" },
  { "name": "British Indian Ocean Territory", "code": "IO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1f4.svg" },
  { "name": "Brunei Darussalam", "code": "BN" },
  { "name": "Bulgaria", "code": "BG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1ec.svg" },
  { "name": "Burkina Faso", "code": "BF", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1eb.svg" },
  { "name": "Burundi", "code": "BI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e7-1f1ee.svg" },
  { "name": "Cambodia", "code": "KH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1ed.svg" },
  { "name": "Cameroon", "code": "CM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1f2.svg" },
  { "name": "Canada", "code": "CA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1e6.svg" },
  { "name": "Cape Verde", "code": "CV", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1fb.svg" },
  { "name": "Cayman Islands", "code": "KY", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1fe.svg" },
  { "name": "Central African Republic", "code": "CF", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1eb.svg" },
  { "name": "Chad", "code": "TD", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1e9.svg" },
  { "name": "Chile", "code": "CL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1f1.svg" },
  { "name": "China", "code": "CN", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1f3.svg" },
  { "name": "Christmas Island", "code": "CX", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1fd.svg" },
  { "name": "Cocos (Keeling) Islands", "code": "CC", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1e8.svg" },
  { "name": "Colombia", "code": "CO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1f4.svg" },
  { "name": "Comoros", "code": "KM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1f2.svg" },
  { "name": "Congo", "code": "CG" },
  { "name": "Congo, The Democratic Republic of the", "code": "CD" },
  { "name": "Cook Islands", "code": "CK", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1f0.svg" },
  { "name": "Costa Rica", "code": "CR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1f7.svg" },
  { "name": "Cote D'Ivoire", "code": "CI" },
  { "name": "Croatia", "code": "HR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ed-1f1f7.svg" },
  { "name": "Cuba", "code": "CU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1fa.svg" },
  { "name": "Cyprus", "code": "CY", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1fe.svg" },
  { "name": "Czech Republic", "code": "CZ" }, { "name": "Denmark", "code": "DK", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e9-1f1f0.svg" },
  { "name": "Djibouti", "code": "DJ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e9-1f1ef.svg" },
  { "name": "Dominica", "code": "DM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e9-1f1f2.svg" },
  { "name": "Dominican Republic", "code": "DO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e9-1f1f4.svg" },
  { "name": "Ecuador", "code": "EC", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ea-1f1e8.svg" },
  { "name": "Egypt", "code": "EG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ea-1f1ec.svg" },
  { "name": "El Salvador", "code": "SV", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1fb.svg" },
  { "name": "Equatorial Guinea", "code": "GQ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1f6.svg" },
  { "name": "Eritrea", "code": "ER", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ea-1f1f7.svg" },
  { "name": "Estonia", "code": "EE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ea-1f1ea.svg" },
  { "name": "Ethiopia", "code": "ET", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ea-1f1f9.svg" },
  { "name": "Falkland Islands (Malvinas)", "code": "FK" },
  { "name": "Faroe Islands", "code": "FO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1eb-1f1f4.svg" },
  { "name": "Fiji", "code": "FJ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1eb-1f1ef.svg" },
  { "name": "Finland", "code": "FI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1eb-1f1ee.svg" },
  { "name": "France", "code": "FR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1eb-1f1f7.svg" },
  { "name": "French Guiana", "code": "GF", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1eb.svg" },
  { "name": "French Polynesia", "code": "PF", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1eb.svg" },
  { "name": "French Southern Territories", "code": "TF", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1eb.svg" },
  { "name": "Gabon", "code": "GA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1e6.svg" },
  { "name": "Gambia", "code": "GM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1f2.svg" },
  { "name": "Georgia", "code": "GE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1ea.svg" },
  { "name": "Germany", "code": "DE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e9-1f1ea.svg" },
  { "name": "Ghana", "code": "GH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1ed.svg" },
  { "name": "Gibraltar", "code": "GI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1ee.svg" },
  { "name": "Greece", "code": "GR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1f7.svg" },
  { "name": "Greenland", "code": "GL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1f1.svg" },
  { "name": "Grenada", "code": "GD", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1e9.svg" },
  { "name": "Guadeloupe", "code": "GP", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1f5.svg" },
  { "name": "Guam", "code": "GU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1fa.svg" },
  { "name": "Guatemala", "code": "GT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1f9.svg" },
  { "name": "Guernsey", "code": "GG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1ec.svg" },
  { "name": "Guinea", "code": "GN", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1f3.svg" },
  { "name": "Guinea-Bissau", "code": "GW", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1fc.svg" },
  { "name": "Guyana", "code": "GY", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1fe.svg" },
  { "name": "Haiti", "code": "HT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ed-1f1f9.svg" },
  { "name": "Heard Island and Mcdonald Islands", "code": "HM" },
  { "name": "Holy See (Vatican City State)", "code": "VA" },
  { "name": "Honduras", "code": "HN", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ed-1f1f3.svg" },
  { "name": "Hong Kong", "code": "HK" },
  { "name": "Hungary", "code": "HU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ed-1f1fa.svg" },
  { "name": "Iceland", "code": "IS", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1f8.svg" },
  { "name": "India", "code": "IN", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1f3.svg" },
  { "name": "Indonesia", "code": "ID", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1e9.svg" },
  { "name": "Iran", "code": "IR" },
  { "name": "Iraq", "code": "IQ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1f6.svg" },
  { "name": "Ireland", "code": "IE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1ea.svg" },
  { "name": "Isle of Man", "code": "IM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1f2.svg" },
  { "name": "Israel", "code": "IL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1f1.svg" },
  { "name": "Italy", "code": "IT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ee-1f1f9.svg" },
  { "name": "Jamaica", "code": "JM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ef-1f1f2.svg" },
  { "name": "Japan", "code": "JP", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ef-1f1f5.svg" },
  { "name": "Jersey", "code": "JE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ef-1f1ea.svg" },
  { "name": "Jordan", "code": "JO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ef-1f1f4.svg" },
  { "name": "Kazakhstan", "code": "KZ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1ff.svg" },
  { "name": "Kenya", "code": "KE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1ea.svg" },
  { "name": "Kiribati", "code": "KI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1ee.svg" },
  { "name": "Korea, Democratic People'S Republic of", "code": "KP" },
  { "name": "Korea, Republic of", "code": "KR" },
  { "name": "Kosovo", "code": "XK" },
  { "name": "Kuwait", "code": "KW", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1fc.svg" },
  { "name": "Kyrgyzstan", "code": "KG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f0-1f1ec.svg" },
  { "name": "Lao People'S Democratic Republic", "code": "LA" },
  { "name": "Latvia", "code": "LV", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1fb.svg" },
  { "name": "Lebanon", "code": "LB", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1e7.svg" },
  { "name": "Lesotho", "code": "LS", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1f8.svg" },
  { "name": "Liberia", "code": "LR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1f7.svg" },
  { "name": "Libyan Arab Jamahiriya", "code": "LY" },
  { "name": "Liechtenstein", "code": "LI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1ee.svg" },
  { "name": "Lithuania", "code": "LT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1f9.svg" },
  { "name": "Luxembourg", "code": "LU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1fa.svg" },
  { "name": "Macao", "code": "MO" },
  { "name": "Macedonia, The Former Yugoslav Republic of", "code": "MK" },
  { "name": "Madagascar", "code": "MG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1ec.svg" },
  { "name": "Malawi", "code": "MW", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1fc.svg" },
  { "name": "Malaysia", "code": "MY", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1fe.svg" },
  { "name": "Maldives", "code": "MV", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1fb.svg" },
  { "name": "Mali", "code": "ML", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1f1.svg" },
  { "name": "Malta", "code": "MT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1f9.svg" },
  { "name": "Marshall Islands", "code": "MH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1ed.svg" },
  { "name": "Martinique", "code": "MQ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1f6.svg" },
  { "name": "Mauritania", "code": "MR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1f7.svg" },
  { "name": "Mauritius", "code": "MU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1fa.svg" },
  { "name": "Mayotte", "code": "YT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fe-1f1f9.svg" },
  { "name": "Mexico", "code": "MX", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1fd.svg" },
  { "name": "Micronesia, Federated States of", "code": "FM" },
  { "name": "Moldova, Republic of", "code": "MD" },
  { "name": "Monaco", "code": "MC", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1e8.svg" },
  { "name": "Mongolia", "code": "MN", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1f3.svg" },
  { "name": "Montserrat", "code": "MS", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1f8.svg" },
  { "name": "Montenegro", "code": "ME" },
  { "name": "Morocco", "code": "MA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1e6.svg" },
  { "name": "Mozambique", "code": "MZ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1ff.svg" },
  { "name": "Myanmar", "code": "MM" },
  { "name": "Namibia", "code": "NA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1e6.svg" },
  { "name": "Nauru", "code": "NR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1f7.svg" },
  { "name": "Nepal", "code": "NP", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1f5.svg" },
  { "name": "Netherlands", "code": "NL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1f1.svg" },
  { "name": "Netherlands Antilles", "code": "AN" },
  { "name": "New Caledonia", "code": "NC", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1e8.svg" },
  { "name": "New Zealand", "code": "NZ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1ff.svg" },
  { "name": "Nicaragua", "code": "NI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1ee.svg" },
  { "name": "Niger", "code": "NE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1ea.svg" },
  { "name": "Nigeria", "code": "NG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1ec.svg" },
  { "name": "Niue", "code": "NU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1fa.svg" },
  { "name": "Norfolk Island", "code": "NF", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1eb.svg" },
  { "name": "Northern Mariana Islands", "code": "MP", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f2-1f1f5.svg" },
  { "name": "North Macedonia", "code": "MK" },
  { "name": "Norway", "code": "NO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f3-1f1f4.svg" },
  { "name": "Oman", "code": "OM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f4-1f1f2.svg" },
  { "name": "Pakistan", "code": "PK", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1f0.svg" },
  { "name": "Palau", "code": "PW", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1fc.svg" },
  { "name": "Palestinian Territory, Occupied", "code": "PS" },
  { "name": "Panama", "code": "PA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1e6.svg" },
  { "name": "Papua New Guinea", "code": "PG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1ec.svg" },
  { "name": "Paraguay", "code": "PY", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1fe.svg" },
  { "name": "Peru", "code": "PE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1ea.svg" },
  { "name": "Philippines", "code": "PH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1ed.svg" },
  { "name": "Pitcairn", "code": "PN" },
  { "name": "Poland", "code": "PL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1f1.svg" },
  { "name": "Portugal", "code": "PT", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1f9.svg" },
  { "name": "Puerto Rico", "code": "PR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f5-1f1f7.svg" },
  { "name": "Qatar", "code": "QA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f6-1f1e6.svg" },
  { "name": "Reunion", "code": "RE" },
  { "name": "Romania", "code": "RO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f7-1f1f4.svg" },
  { "name": "Russian Federation", "code": "RU" },
  { "name": "RWANDA", "code": "RW" },
  { "name": "Saint Helena", "code": "SH" },
  { "name": "Saint Kitts and Nevis", "code": "KN" },
  { "name": "Saint Lucia", "code": "LC" },
  { "name": "Saint Pierre and Miquelon", "code": "PM" },
  { "name": "Saint Vincent and the Grenadines", "code": "VC" },
  { "name": "Samoa", "code": "WS", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fc-1f1f8.svg" },
  { "name": "San Marino", "code": "SM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1f2.svg" },
  { "name": "Sao Tome and Principe", "code": "ST" },
  { "name": "Saudi Arabia", "code": "SA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1e6.svg" },
  { "name": "Senegal", "code": "SN", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1f3.svg" },
  { "name": "Serbia", "code": "RS" },
  { "name": "Serbia and Montenegro", "code": "CS" },
  { "name": "Seychelles", "code": "SC", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1e8.svg" },
  { "name": "Sierra Leone", "code": "SL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1f1.svg" },
  { "name": "Singapore", "code": "SG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1ec.svg" },
  { "name": "Slovakia", "code": "SK", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1f0.svg" },
  { "name": "Slovenia", "code": "SI", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1ee.svg" },
  { "name": "Solomon Islands", "code": "SB", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1e7.svg" },
  { "name": "Somalia", "code": "SO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1f4.svg" },
  { "name": "South Africa", "code": "ZA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ff-1f1e6.svg" },
  { "name": "South Georgia and the South Sandwich Islands", "code": "GS" },
  { "name": "Spain", "code": "ES", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ea-1f1f8.svg" },
  { "name": "Sri Lanka", "code": "LK", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f1-1f1f0.svg" },
  { "name": "Sudan", "code": "SD", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1e9.svg" },
  { "name": "South Sudan", "code": "SS" },
  { "name": "Suriname", "code": "SR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1f7.svg" },
  { "name": "Svalbard and Jan Mayen", "code": "SJ" },
  { "name": "Swaziland", "code": "SZ" },

  { "name": "Sweden", "code": "SE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f8-1f1ea.svg" },
  { "name": "Switzerland", "code": "CH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e8-1f1ed.svg" },
  { "name": "Syrian Arab Republic", "code": "SY" },
  { "name": "Taiwan, Province of China", "code": "TW" },
  { "name": "Tajikistan", "code": "TJ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1ef.svg" },
  { "name": "Tanzania, United Republic of", "code": "TZ" },
  { "name": "Thailand", "code": "TH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1ed.svg" },
  { "name": "Timor-Leste", "code": "TL", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1f1.svg" },
  { "name": "Togo", "code": "TG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1ec.svg" },
  { "name": "Tokelau", "code": "TK", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1f0.svg" },
  { "name": "Tonga", "code": "TO", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1f4.svg" },
  { "name": "Trinidad and Tobago", "code": "TT" },
  { "name": "Tunisia", "code": "TN", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1f3.svg" },

  { "name": "Turkey", "code": "TR", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1f7.svg" },
  { "name": "Turkmenistan", "code": "TM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1f2.svg" },
  { "name": "Turks and Caicos Islands", "code": "TC" },
  { "name": "Tuvalu", "code": "TV", "flag": "https://twemoji.maxcdn.com/2/svg/1f1f9-1f1fb.svg" },
  { "name": "Uganda", "code": "UG", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fa-1f1ec.svg" },
  { "name": "Ukraine", "code": "UA", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fa-1f1e6.svg" },
  { "name": "United Arab Emirates", "code": "AE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1e6-1f1ea.svg" },
  { "name": "United Kingdom", "code": "GB", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ec-1f1e7.svg" },
  { "name": "United States", "code": "US", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fa-1f1f8.svg" },
  { "name": "United States Minor Outlying Islands", "code": "UM" },
  { "name": "Uruguay", "code": "UY", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fa-1f1fe.svg" },
  { "name": "Uzbekistan", "code": "UZ", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fa-1f1ff.svg" },
  { "name": "Vanuatu", "code": "VU", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fb-1f1fa.svg" },
  { "name": "Venezuela", "code": "VE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fb-1f1ea.svg" },
  { "name": "Viet Nam", "code": "VN" },
  { "name": "Virgin Islands, British", "code": "VG" },
  { "name": "Virgin Islands, U.S.", "code": "VI" },
  { "name": "Wallis and Futuna", "code": "WF" },
  { "name": "Western Sahara", "code": "EH", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ea-1f1ed.svg" },
  { "name": "Yemen", "code": "YE", "flag": "https://twemoji.maxcdn.com/2/svg/1f1fe-1f1ea.svg" },
  { "name": "Zambia", "code": "ZM", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ff-1f1f2.svg" },
  { "name": "Zimbabwe", "code": "ZW", "flag": "https://twemoji.maxcdn.com/2/svg/1f1ff-1f1fc.svg" }
];

export default countries;