export enum BID_TYPES {
    BID = 'BID',
    LEADS = 'LEADS',
    JOBS = 'JOBS',
    ALL = 'ALL'
}

export enum DEAL_LOG_TYPE {
    BID_CREATED = 'BID_CREATED',
    BID_UPDATED = 'BID_UPDATED',
    LEAD_SYNCED = 'LEAD_SYNCED',
    LEAD_UPDATED = 'LEAD_UPDATED',
    JOB_CREATED = 'JOB_CREATED',
    JOB_UPDATED = 'JOB_UPDATED',
    CLICKUP_TASK_CREATED = 'CLICKUP_TASK_CREATED',
    HUBSPOT_DEAL_CREATED = 'HUBSPOT_DEAL_CREATED',
    FIELD_UPDATED = 'FIELD_UPDATED',

}

export enum ACCOUNT_LOG_TYPE {
    ACCOUNT_CREATED = 'CONTACT_CREATED',
    ACCOUNT_UPDATED = 'CONTACT_UPDATED',
    ACCOUNT_DELETED = 'CONTACT_DELETED',
}


export enum LEADS_TYPE {
    LEADS = 'LEADS',
    INVITES = 'INVITES',
    INVITE_ONLY = 'INVITE_ONLY',
    ALL = 'ALL'
}