import React, { useState } from "react";
import FAQItem from "../common/FAQItem";

export default function FAQQRCodeGenerator() {
  const [openQuestionIndex, setOpenQuestionIndex] = useState<number | null>(
    null,
  );

  const toggleQuestion = (index: number) => {
    if (openQuestionIndex === index) {
      setOpenQuestionIndex(null);
    } else {
      setOpenQuestionIndex(index);
    }
  };

  const faqData = [
    {
      question: "Is ToolChimp's QR Code Generator free to use?",
      answer:
        "Absolutely! ToolChimp provides a free online service that allows you to generate QR codes without any cost.",
    },
    {
      question: "What can I use ToolChimp's QR Code Generator for?",
      answer:
        "You can use our QR Code Generator to create QR codes for URLs, text, contact information, and more, making it easy to share and store information.",
    },
    {
      question: "Can I customize the QR codes generated by ToolChimp?",
      answer:
        "Currently, ToolChimp's QR Code Generator offers basic QR code generation without customization options. Stay tuned for future updates with more features!",
    },
    {
      question: "Is ToolChimp's QR Code Generator easy to use?",
      answer:
        "Yes, ToolChimp's QR Code Generator is designed to be user-friendly. Simply enter the information you want to encode, and the QR code will be generated instantly.",
    },
    {
      question: "Can I download the generated QR code?",
      answer:
        "Yes, once you generate a QR code, you can download it as an image file to use in your projects or share with others.",
    },
    {
      question: "Is ToolChimp's QR Code Generator safe to use?",
      answer:
        "ToolChimp is a safe and secure service, free from viruses, and operates under strict security protocols. However, always exercise caution when using any online tool and ensure your device has up-to-date security software.",
    },
  ];

  return (
    <div className="bg-[#212121] text-white w-full mt-10">
      <div className="container mx-auto py-12">
        <h2 className="text-3xl font-bold mb-8 text-center">
          Frequently Asked Questions
        </h2>
        <div className="bg-gray-800 rounded-lg shadow-lg p-6">
          {faqData.map((faq, index) => (
            <FAQItem
              key={index}
              index={index}
              question={faq.question}
              answer={faq.answer}
              openQuestionIndex={openQuestionIndex}
              toggleQuestion={toggleQuestion}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
