const mongoHost = process.env.VUE_APP_MONGO_URL
const restatHost = process.env.VUE_APP_BASE_URL

const MESSAGES = {
    SYNC_PROPOSAL: "sync-proposal",
    SYNC_LEAD: "sync-lead",
    SYNC_CONTRACT: "sync-contract",
    SYNC_PROPOSAL_SUCCESS: "sync-proposal-success",
    SYNC_PROPOSAL_ERROR: "sync-proposal-error",
    SYNC_LEAD_SUCCESS: "sync-lead-success",
    SYNC_LEAD_ERROR: "sync-lead-error",
    SYNC_CONTRACT_SUCCESS: "sync-contract-success",
    SYNC_CONTRACT_ERROR: "sync-contract-error",
    SYNC_CONNECT: "sync-connect",
    SYNC_PROSPECT: "sync-prospect",
    SYNC_MESSAGES: "sync-messages",
    SYNC_CONNECT_SUCCESS: "sync-connect-success",
    SYNC_CONNECT_ERROR: "sync-connect-error",
    SYNC_PROSPECT_SUCCESS: "sync-prospect-success",
    SYNC_PROSPECT_ERROR: 'sync-prospect-error',
    ADD_COVER_LETTER_TEMPLATE: "add-cover-letter-template",
    UPDATE_BADGE: "update-badge",
    ADD_BUTTONS: "add-buttons",
    REMOVE_BUTTONS: "remove-buttons",
    ADD_BUTTONS_SUCCESS: "add-buttons-success",
    REMOVE_BUTTONS_SUCCESS: "remove-buttons-success",
    SHOW_SIDE_PANEL: "show-side-panel",
    CHECK_CONTENT_SCRIPT: "check-content-script",
    CONTENT_SCRIPT_LOADED: "content-script-loaded",
    UPDATE_UPWORK_PROFILE: "update-upwork-profile",
    UPDATE_LINKEDIN_PROFILE: "update-linkedin-profile",
    ALERT_CURRENT_TAB: "alert-current-tab",
    UPDATE_COUNT: "update-count",
    SOCIAL_LOGIN: 'restat-social-login',
    LOGIN_SUCCESS: 'login-success'
}

const BUTTON_NAMES = {
    SYNC_PROPOSAL: "Sync Proposal",
    SYNC_LEAD: "Sync Lead",
    SYNC_CONTRACT: "Sync Contract",
    SYNC_CONNECT: "Sync Connection",
    SYNC_PROSPECT: "Sync Prospect",
    SYNC_MESSAGES: "Sync Messages"
}

const BUTTONS = {
    SYNC_PROPOSAL: "restat-upwork-sync-proposal-button",
    SYNC_LEAD: "restat-upwork-sync-lead-button",
    SYNC_CONTRACT: "restat-upwork-sync-contract-button",
    SYNC_CONNECT: "restat-linkedin-sync-connect-button",
    SYNC_PROSPECT: "restat-linkedin-sync-prospect-button",

}

const PATTERNS = {
    UPWORK: /https:\/\/www.upwork.com\/*/,
    SUBMIT_PROPOSAL: /https:\/\/www\.upwork\.com\/.*\/proposals\/job\/~.*\/apply\//,
    PROPOSAL_DETAILS: /https:\/\/www\.upwork\.com\/.*\/proposals\/.+$/,
    PROPOSAL_EDIT: /https:\/\/www\.upwork\.com\/.*\/proposals\/\d+\/edit$/,
    PROPOSAL_INSIGHTS: /https:\/\/www\.upwork\.com\/.*\/proposals\/insights\/\d+$/,
    LINKEDIN: /https:\/\/www.linkedin.com\/*/,
    LINKEDIN_PROFILE: /https:\/\/www.linkedin.com\/in\/*/,
}

const TARGET = {
    UNSET: "No Target"
}

const ALARMS = {
    DAILY_UPDATE: "dailyUpdate"
}


const SOURCE = {
    UPWORK: "UPWORK",
    LINKEDIN: "LINKEDIN"
}

const TABS = {
    UPWORK: "UPWORK",
    LINKEDIN: "LINKEDIN"
}

const OUTER_TAB = {
    SETTINGS: "settings"
}

const STORAGE = {
    USER_TOKEN: "userToken",
    BIDDER: "bidder",
    COMPANY: "company",
    SETTINGS: "settings",
    LINKEDIN_TARGET: "linkedinTarget",
    UPWORK_TARGET: "upworkTarget",
    UPWORK_PROFILE: "upworkProfile",
    LINKEDIN_PROFILE: "linkedinProfile",
    INDUSTRY: "industry",
    BID_DAILY_COUNT: "bidDailyCount",
    BID_MONTHLY_COUNT: "bidMonthlyCount",
    LEAD_DAILY_COUNT: "leadDailyCount",
    LEAD_MONTHLY_COUNT: "leadMonthlyCount",
    LINKEDIN_CONNECT_DAILY_COUNT: "linkedinConnectDailyCount",
    LINKEDIN_CONNECT_MONTHLY_COUNT: "linkedinConnectMonthlyCount",
    LINKEDIN_PROSPECT_DAILY_COUNT: "linkedinProspectDailyCount",
    LINKEDIN_PROSPECT_MONTHLY_COUNT: "linkedinProspectMonthlyCount",
    CONNECT_OBJ_ARRAY: "connectsObjArr"
}
const countryNames = {
    "Afghanistan": "Afghanistan",
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antigua and Barbuda",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaijan",
    "Bahamas": "Bahamas",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Belarus",
    "Belgium": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivia": "Bolivia",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazil": "Brazil",
    "Brunei": "Brunei",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Cabo Verde",
    "Cambodia": "Cambodia",
    "Cameroon": "Cameroon",
    "Canada": "Canada",
    "Central African Republic": "Central African Republic",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Colombia": "Colombia",
    "Comoros": "Comoros",
    "Congo": "Congo",
    "Congo (Democratic Republic)": "Congo (Democratic Republic)",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croatia",
    "Cuba": "Cuba",
    "Cyprus": "Cyprus",
    "Czech Republic": "Czech Republic",
    "Denmark": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominican Republic": "Dominican Republic",
    "East Timor": "East Timor",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatorial Guinea",
    "Eritrea": "Eritrea",
    "Estonia": "Estonia",
    "Eswatini": "Eswatini",
    "Ethiopia": "Ethiopia",
    "Fiji": "Fiji",
    "Finland": "Finland",
    "France": "France",
    "Gabon": "Gabon",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Germany": "Germany",
    "Ghana": "Ghana",
    "Greece": "Greece",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungary": "Hungary",
    "Iceland": "Iceland",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Iran",
    "Iraq": "Iraq",
    "Ireland": "Ireland",
    "Israel": "Israel",
    "Italy": "Italy",
    "Jamaica": "Jamaica",
    "Japan": "Japan",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kiribati": "Kiribati",
    "Korea (North)": "Korea (North)",
    "Korea (South)": "Korea (South)",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kyrgyzstan",
    "Laos": "Laos",
    "Latvia": "Latvia",
    "Lebanon": "Lebanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libya": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Maldives": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marshall Islands": "Marshall Islands",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexico": "Mexico",
    "Micronesia": "Micronesia",
    "Moldova": "Moldova",
    "Monaco": "Monaco",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Morocco",
    "Mozambique": "Mozambique",
    "Myanmar": "Myanmar",
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Netherlands": "Netherlands",
    "New Zealand": "New Zealand",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "North Macedonia": "North Macedonia",
    "Norway": "Norway",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Palau": "Palau",
    "Panama": "Panama",
    "Papua New Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Poland": "Poland",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russia": "Russia",
    "Rwanda": "Rwanda",
    "Saint Kitts and Nevis": "Saint Kitts and Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tome and Principe",
    "Saudi Arabia": "Saudi Arabia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapore",
    "Slovakia": "Slovakia",
    "Slovenia": "Slovenia",
    "Solomon Islands": "Solomon Islands",
    "Somalia": "Somalia",
    "South Africa": "South Africa",
    "Spain": "Spain",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Sweden": "Sweden",
    "Switzerland": "Switzerland",
    "Syria": "Syria",
    "Taiwan": "Taiwan",
    "Tajikistan": "Tajikistan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailand",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tunisia": "Tunisia",
    "Turkey": "Turkey",
    "Turkmenistan": "Turkmenistan",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ukraine": "Ukraine",
    "United Arab Emirates": "United Arab Emirates",
    "United Kingdom": "United Kingdom",
    "United States": "United States",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Vatican City": "Vatican City",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Yemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe"
  };
  
export { mongoHost, restatHost, MESSAGES, BUTTON_NAMES, BUTTONS, PATTERNS, TARGET, ALARMS, TABS, SOURCE, OUTER_TAB, STORAGE, countryNames };
