name: CI

on: 
  push:
    branches:
      - none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute ssh command via using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.CICD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /mnt/ext_js/restat/frontend
            ./deploy-script.sh